### ISSUE TITLE
How can i make csv from data of cellranger?

### ISSUE THREAD

**Issue by kysbbubbu** [10XGenomics/cellranger#10]
How can i make csv from data of cellranger?

I am now handling the single cell expression data of 2000 to 3000 cells from cell line 

I tried cellranger mat2csv order, but it did not work may be due to memory problem 

Otherwise, if i could modify mtx data such as removing null data and normalizing, i think that csv converting might be possible.

Is there any suggest for me?

**Comment by malbahrani** [comment]
@kysbbubbu Could you post the error message you get, otherwise it will be hard to specify the source of the problem.
 I recently was able to use `mat2csv` successfully on `.mtx` file, but I had to make sure that I give the right arguments.

**Comment by SinghalDivya** [comment]
@malbahrani Could you please tell me what right arguments you used to convert a .mtx file to .csv format using mat2csv?
because I am trying to do the same but it's throwing me IOerror.

**Comment by malbahrani** [comment]
@SinghalDivya 

Sorry for the delayed response.  Have you tried this:

`cellranger mat2csv [type the path to the .mtx file] [type the path to the output file]`

As an example, let say you have the .mtx file under `/data` directory. And you have created `output` directory to save in the `.csv` file that cellranger will generate: 

`cellranger mat2csv ../data/ ../output/matrix.csv`

Please let me know if you still have issues running the commands.

**Comment by evolvedmicrobe** [comment]
Thanks for the responses here, looks like this issue was solved or has not been responded to for several months so will close this.
