### ISSUE TITLE
Cellranger5.0.0 mkref do not generate genes.pickle file (and repertory)

### ISSUE THREAD

**Issue by newbieMars** [10XGenomics/cellranger#104]
Hi @Cellranger_team,

First thanks for your great tool and the useful upgrades you still propose to the community.
I'm facing a pb with the new Cellranger5.0.0 mkref when I want to add eYFP gene to mouse genome (the last version proposed with cellranger5.0.0). When I launch mkref, it generates all the files (and repertories) expected  except pickle repertory and its associated genes.pickle file leading to errors when trying to launch cellranger multi (or count). I've tried the same script whith cellranger3.1.0 and it works well generating all the expected files included genes.pickle.

Do you have any suggestion?

Estelle

**Comment by evolvedmicrobe** [comment]
Hi Estelle, what error are you getting? We deprecated the genes.pickle file and now just generate it on the fly.

**Comment by evolvedmicrobe** [comment]
Closing this issue, but if you have further questions please contact support@10xgenomics.com
