### ISSUE TITLE
unknown error when running 'testrun' with CellRanger

### ISSUE THREAD

**Issue by mengm5** [10XGenomics/cellranger#105]
Hi @Cellranger_team,
Firstly, thank you for your great job in CellRanger.
Here is an error when using CellRanger and I don't know how to sovle it, the error is:

2020-12-03 07:36:55 [runtime] (failed)          ID.S01-GEX.SC_RNA_COUNTER_CS.SC_MULTI_CORE.MULTI_GEM_WELL_PROCESSOR.COUNT_GEM_WELL_PROCESSOR._BASIC_SC_RNA_COUNTER._CELLS_REPORTER.SUBSAMPLE_READS

[error] Pipestance failed. Error log at:
S01-GEX/SC_RNA_COUNTER_CS/SC_MULTI_CORE/MULTI_GEM_WELL_PROCESSOR/COUNT_GEM_WELL_PROCESSOR/_BASIC_SC_RNA_COUNTER/_CELLS_REPORTER/SUBSAMPLE_READS/fork0/chnk0-u82dec82511/_errors

Log message:
Job failed in stage code

exit status 1

I use 'cellranger testrun --id=tiny' for checking system, but it also turns up error, please see pic.

![kjjk](https://user-images.githubusercontent.com/31919733/100956743-1de4f000-3554-11eb-878e-d34c9ecc2afe.png)

Information:
CellRanger version: CellRanger 5.0.0
system information: centos7_7(x86_64), 32 CPU, 64G.
command: cellranger count --include-introns --nosecondary --no-bam --localcores 30 --localmem 60 --id=S01-GEX --sample=S01-GEX --fastqs=fq_path --transcriptome=ref_path/refdata-gex-GRCh38-2020-A
fastq:
S01-GEX_S1_L001_R1_001.fastq.gz
S01-GEX_S1_L001_R2_001.fastq.gz
S01-GEX_S1_L002_R1_001.fastq.gz
S01-GEX_S1_L002_R2_001.fastq.gz
S01-GEX_S1_L003_R1_001.fastq.gz
S01-GEX_S1_L003_R2_001.fastq.gz
S01-GEX_S1_L004_R1_001.fastq.gz
S01-GEX_S1_L004_R2_001.fastq.gz

Could you give me some suggestions?
Thanks again!
mengm

**Comment by evolvedmicrobe** [comment]
Hi, please contact support@10xgenomics.com for help with this issue, the upload would be very useful in helping to diagnose.
