### ISSUE TITLE
a piece of information about AGGR

### ISSUE THREAD

**Issue by tanasa** [10XGenomics/cellranger#106]
Dear all,

would you please let me know how precisely the normalization works when combining two scRNA-seq samples with CELLAGGR ?
if you could let me know the mathematical formula, or offer an example on two very small matrices, it would be extraordinary.

many thanks,

-- bogdan

**Comment by evolvedmicrobe** [comment]
Hi Bogdan,

Please see the section on Depth Normalization here: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/aggregate for a description, if you have any further questions please reach out to support@10xgenomics.com for further insights.

Warm wishes,
N

**Comment by tanasa** [comment]
thank you very much Nigel !
