### ISSUE TITLE
high variable genes

### ISSUE THREAD

**Issue by wangjiawen2013** [10XGenomics/cellranger#108]
Hi,
Seurat and scanpy often select high variable genes for the downstream analysis. Which genes cellranger uses to perfrom dimensionality reduction ?

**Comment by evolvedmicrobe** [comment]
Cell Ranger uses all genes with effectively non-zero UMI counts in the matrix for downstream dimensionality reduction.  The PCA methods it uses can perform dimensionality reduction on full matrices, and in general genes with little variance do not contribute much to the top PCs relative to those that do.
