### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by carandraug** [10XGenomics/cellranger#11]
The LICENSE file mentions that the license for the louvain code is under LGPLv3 and GPLv3.  The directory `lib/louvain` indeed has a file for both licenses but all individual files reference only the LGPLv3. Can you clarify the license of those files?

The LICENSE file also mentions that the rest of the code is under AGPLv2 but the individual files have the much less clear "all rights reserved" with no mention of the license. Making things a bit more confusing there's also `lib/python/cellranger/analysis/irlb.py` which claims to be under Apache 2 and `lib/python/cellranger/webshim/lz_string.py` being based on http://pieroxy.net/blog/pages/lz-string/index.html which is under WTFPL. The FSF [how to use GNU licenses](https://www.gnu.org/licenses/gpl-howto.html)  mentions that each file should have the license notice to make this clearer, which would be nice. Could all files files under AGPLv2 and owned by 10x genomics, Inc have the license notice to make things clearer?

The LICENSE file also mentions Laurens van der Maaten from Delft University reserving all rights of tsne for himself. I couldn't find the tsne code on the repository. Laurens van der Maaten has a [python tsne module online](https://lvdmaaten.github.io/tsne/code/tsne_python.zip) but in there, the copyright is claimed by Tilburg University not Delft. The binary releases of cell ranger include a tsne module by Daniel Rodriguez. The PKG_INFO of that package claims to be under Apache 2. However, the [LICENSE file on his repository](https://github.com/danielfrg/tsne/blob/master/LICENSE) have 4-clause BSD license (which by the way, [is GPL and AGPL incompatible](https://www.gnu.org/licenses/license-list.en.html#OriginalBSD)).

**Comment by carandraug** [comment]
For what is worth, I'm looking into this because I'm investigating if I can package cellranger for Debian.

**Comment by evolvedmicrobe** [comment]
Hi, please reach out to support@10xgenomics.com with licensing questions for a timely response.
