### ISSUE TITLE
Edit loupe files

### ISSUE THREAD

**Issue by brianpenghe** [10XGenomics/cellranger#111]
Do you know what tools can I use to edit loupe files?
I want to manually add scores for cells.

Thanks

**Comment by evolvedmicrobe** [comment]
Loupe files are not designed to be manually edited, but it is possible to make changes through the UI, please reach out to support@10xgenomics.com for more help.

**Comment by brianpenghe** [comment]
But the UI doesn't allow us to add continuous scores - only categories are allowed to be added. That makes it very difficult to include probabilities of cell types for each Visium spot to be assigned!
