### ISSUE TITLE
cellranger count: ERROR : --transcriptome NO such file or directory 

### ISSUE THREAD

**Issue by MubasherMohammed** [10XGenomics/cellranger#113]
Hi, I run into ERROR while using cellranger count function for genome alignment and its "NO such file or directory" for the transcriptome I couldn't figure it out as I make sure the path is correct

##command 
cellranger count --id=10xgam_count \
                   --fastqs=/crex/proj/uppstore2019072/10xgams/TH-2632/200922_A00181_0206_AHT2VJDRXX/ \
                   --sample=SI-GA-B1_1,SI-GA-B1_2,SI-GA-B1_3,SI-GA-B1_4,SI-GA-C1_1,SI-GA-C1_2,SI-GA-C1_3,SI-GA-C1_4
                   --transcriptome=/crex/proj/uppstore2019072/10xgams/TH-2632/Sanger-data/Plasmodium_falciparum.ASM276v2_MM \
                   --expect-cells=1000 \
                   --localcores=26 \
                   --localmem=500

## ERROR 

For more information try --help
/var/spool/slurmd/job18829903/slurm_script: line 21: --transcriptome=/crex/proj/uppstore2019072/10xgams/TH-2632/Sanger-data/Plasmodium_falciparum.ASM276v2_MM: No such file or directory

**Comment by evolvedmicrobe** [comment]
Hi, please reach out to support@10xgenomics.com for additional help on this, at first glance I'd be curious if there were any symlinks in the path name.
