### ISSUE TITLE
Pipestance failed

### ISSUE THREAD

**Issue by yuyingxie** [10XGenomics/cellranger#114]
Dear Cellranger,

I am running the following codes to process my fastq data

cellranger count --id=Sample8_GE \
                  --transcriptome=refdata-gex-mm10-2020-A \
                  --fastqs=Sample_2571-YL-22 \
                  --localcores=8 \
                  --localmem=64
                
and got the following error message

2021-03-15 11:41:47 [runtime] (failed)          ID.Sample5_GE.SC_RNA_COUNTER_CS.SC_MULTI_CORE.MULTI_GEM_WELL_PROCESSOR.COUNT_GEM_WELL_PROCESSOR._BASIC_SC_RNA_COUNTER._MATRIX_COMPUTER.MAKE_SHARD

[error] Pipestance failed. Error log at:
Sample5_GE/SC_RNA_COUNTER_CS/SC_MULTI_CORE/MULTI_GEM_WELL_PROCESSOR/COUNT_GEM_WELL_PROCESSOR/_BASIC_SC_RNA_COUNTER/_MATRIX_COMPUTER/MAKE_SHARD/fork0/chnk0-u01d54f79de/_errors

Log message:
stage failed unexpectedly: 'internal error: entered unreachable code' execroot/home/registry/src/github.com-1ecc6299db9ec823/shardio-0.7.3/src/lib.rs:411:
   0: martian::martian_entry_point::{{closure}}
             at execroot/exec/lib/rust/execroot/home/git/checkouts/martian-rust-35615836cc90309f/8b43658/martian/src/lib.rs:184:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597:17
   2: std::panicking::begin_panic::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:522:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
   4: std::panicking::begin_panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:521:12
   5: shardio::BufferStateMachine<T,H>::close
             at execroot/exec/lib/rust/execroot/home/registry/src/github.com-1ecc6299db9ec823/shardio-0.7.3/src/lib.rs:411:37
      shardio::ShardWriterInner<T,S>::close
             at execroot/exec/lib/rust/execroot/home/registry/src/github.com-1ecc6299db9ec823/shardio-0.7.3/src/lib.rs:656:27
      shardio::ShardWriter<T,S>::finish
             at execroot/exec/lib/rust/execroot/home/registry/src/github.com-1ecc6299db9ec823/shardio-0.7.3/src/lib.rs:249:30
   6: <shardio::ShardWriter<T,S> as core::ops::drop::Drop>::drop
             at execroot/exec/lib/rust/execroot/home/registry/src/github.com-1ecc6299db9ec823/shardio-0.7.3/src/lib.rs:271:18
      core::ptr::drop_in_place
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ptr/mod.rs:175:1
      core::ptr::drop_in_place
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ptr/mod.rs:175:1
   7: core::ptr::drop_in_place
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ptr/mod.rs:175:1
      <cr_lib::make_shard::MakeShard as martian::stage::MartianStage>::main
             at execroot/exec/lib/rust/cr_lib/src/make_shard.rs:274:5
   8: <T as martian::stage::RawMartianStage>::main
             at execroot/exec/lib/rust/execroot/home/git/checkouts/martian-rust-35615836cc90309f/8b43658/martian/src/stage.rs:642:20
   9: martian::martian_entry_point
             at execroot/exec/lib/rust/execroot/home/git/checkouts/martian-rust-35615836cc90309f/8b43658/martian/src/lib.rs:225:9
      martian::MartianAdapter<S>::run_get_error
             at execroot/exec/lib/rust/execroot/home/git/checkouts/martian-rust-35615836cc90309f/8b43658/martian/src/lib.rs:131:9
      martian::MartianAdapter<S>::run
             at execroot/exec/lib/rust/execroot/home/git/checkouts/martian-rust-35615836cc90309f/8b43658/martian/src/lib.rs:124:9
      cr_lib::main
             at execroot/exec/lib/rust/cr_lib/src/bin/cr_lib.rs:111:23
  10: core::ops::function::FnOnce::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:227:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:125:18
  11: main
  12: __libc_start_main
  13: <unknown>
             at /mnt/home/adam.azarchs/crosstool/build/src/glibc-2.12.2/csu/../sysdeps/x86_64/elf/start.S:103

Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

Can you help me to debug it?

Thanks so much for your help.

Yuying

**Comment by evolvedmicrobe** [comment]
Please contact support@10xgenomics.com for help with this issue, at first glance it looks like a transient file system error, but they'll be able to help you track this down.

**Comment by zgyaru** [comment]
Hi Yuying,
I have countered the same error. Did you fix it?

**Comment by plijnzaad** [comment]
Hi all, 

I occasionally get very similar crashes. I suspect NFS may be part of the problem, perhaps in conjunction with very long filenames / pathnames. Would very much like to see this solved ...

**Comment by erlun1** [comment]
I confirm that this issue is due to insufficient disk space allocated to cellranger.
