### ISSUE TITLE
10x 5prime results reproducibility

### ISSUE THREAD

**Issue by Hoohm** [10XGenomics/cellranger#12]
Hello @pryvkin10x 
I have put together a [scRNAseq pipeline](https://github.com/Hoohm/dropSeqPipe) that is compatible with 10x 3' chemistry and outputs comparable results to cellranger.

I have tried to run it with 10x 5' data, but I get way less genes/cell. I have looked at the chemistry of the 5' and the source code of cellranger but haven't been able to determine what the problem seems to be.

Would you have some insights as to what part I should look into?

**Comment by pryvkin10x** [comment]
Sorry for the delayed response - just saw this.

Bear in mind that unlike 3', 5' can be run with two alignable reads per read-pair (i.e., you can use paired-end alignment). But that is only possible if the library was sequenced past cycle 26 on R1.

If R1 was sequenced past cycle 26, and you're trying to align it, you may want to try trimming the following 13 bases of R1 as there's a constant non-genomic sequence there.
