### ISSUE TITLE
cellranger count How to modify the output path

### ISSUE THREAD

**Issue by yanglq-bio** [10XGenomics/cellranger#124]
Hi,
I’m using the Cellranger(the version is 6.6.0),When I running cellranger count --help,I can't find any parameters to modify the output path.

so,I want to know How can I change it.

**Comment by mmfalco** [comment]
Have you tried specifying the path in the `--id`(e.g. `--id=/path/to/output/sample1`) parameter?

**Comment by evolvedmicrobe** [comment]
We don't have a CR version `6.6.0` so am a little confused by that.  As @mmfalco mentions, the `--id` parameter determines what the output folder is, though you cannot specify subdirectories, as `'--id <ID>': must contain only letters, digits, underscores, and dashes.`

**Comment by yanglq-bio** [comment]
yes ,I tried it.but got error


| |
elaine
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/20/2021 ***@***.***> wrote：

Have you tried specifying the path in the --id(e.g. --id=/path/to/output/sample1) parameter?
