### ISSUE TITLE
[error] Your reference doesn't appear to be indexed. Please run the mkref tool.

### ISSUE THREAD

**Issue by lwtan90** [10XGenomics/cellranger#131]
Hi,

I am using cellranger-atac count. Also, I downloaded the precompiled reference (refdata-cellranger-arc-GRCh38-2020-A-2.0.0), and unpacked it. My cellranger-atac version is 1.1.0.

However, I am getting this error message to run mkref tool. In the fasta folder, I can clearly see .fai file which means the genome.fa has been indexed.

Is there a workaround?
Thanks.

**Comment by plbaldoni** [comment]
I am having the same issue. It seems that the error is coming from [here](https://github.com/10XGenomics/cellranger/blob/a83c753ce641db6409a59ad817328354fbe7187e/tenkit/lib/python/tenkit/preflight.py#L153-L155)

**Comment by lwtan90** [comment]
And they dont respond to questions?

**Comment by evolvedmicrobe** [comment]
Hi @lwtan90 and @plbaldoni,

For a timely response to any questions, please contact support@10xgenomics.com to get in touch with our support group. `cellranger arc` and `cellranger atac 1.1` use different reference files, so you'll want to use the download from here instead: 

https://support.10xgenomics.com/single-cell-atac/software/downloads/1.1/
