### ISSUE TITLE
How long does mkref run?

### ISSUE THREAD

**Issue by rtyags** [10XGenomics/cellranger#132]
Hi,

I am running cellranger-arc mkref with a modified hg19 genome. It seems to be running for almost 24 hrs now, but no new output seems to have resulted. Is this expected? How long does mkref usually take to run for a human-sized genome? 

FWIW, the last line in Log.out is : "sorting Suffix Array chunks and saving them to disk..."

**Comment by evolvedmicrobe** [comment]
It can take awhile on old hardware or with fewer threads.
