### ISSUE TITLE
better error message than "Formatting error in sample sheet"

### ISSUE THREAD

**Issue by slowkow** [10XGenomics/cellranger#134]
I think we can do better than giving this error:

https://github.com/10XGenomics/cellranger/blob/e6517cae10b030973968dec91e09710063297fde/tenkit/mro/stages/make_fastqs/make_fastqs_preflight_local/__init__.py#L62

I got this error for a `_rna_bcl.csv` file when I ran cellranger, and it didn't help to find the underlying problem.

So, I manually ran `tk_sheet.file_is_simple_samplesheet(csv_path)` on my file. Here's what I got:

```
WARNING:root:Unrecognized sample index: SI-TT-I9
WARNING:root:Unrecognized sample index: SI-TT-I10
WARNING:root:Unrecognized sample index: SI-TN-D8
WARNING:root:Unrecognized sample index: SI-TN-D9
```

This is helpful! We can check and see that `SI-TT-I9` is not a valid sample index.

Now, I hope my cellranger run will finish without error if I fix this sample index.

It'd be ideal if the original error message would include this information.

**Comment by davemcg** [comment]
Much appreciated Kamil - I was getting this error and your post helped me realize that it appears the sequencing center gave me the wrong indexes....
