### ISSUE TITLE
warning in running prefilight checks: problem fetching io 

### ISSUE THREAD

**Issue by juneE-cloud** [10XGenomics/cellranger#135]
![1629957898(1)](https://user-images.githubusercontent.com/84324404/130909613-886592dd-b791-4542-a90d-51c30a6da6ae.png)

Has anyone come across this issue? 

i've already checked all the paths and files and they have nothing wrong. How come i have this warning?

The code is still running in the terminal, i'm wondering if this warning has some impact on my final outcome. 

Looking for your kind reply.
Thank you so much!

**Comment by evolvedmicrobe** [comment]
Closing this issue, @juneE-cloud please reach out to support@10xgenomics for help, and I hope you're having a good experience with Cell Ranger at the moment.

**Comment by juneE-cloud** [comment]
> Closing this issue, @juneE-cloud please reach out to support@10xgenomics for help, and I hope you're having a good experience with Cell Ranger at the moment.

okay, thank you so much!
