### ISSUE TITLE
dnase peaks information

### ISSUE THREAD

**Issue by rtyags** [10XGenomics/cellranger#136]
Hi,

I notice that v2.0 doesn't include dnase.bed information, leading to all 0s in the result table. Is there a reason why this was removed? Can I use a custom reference with dnase.bed file included? 

Thanks

**Comment by brettolsen** [comment]
We found that the DNAse reference files were not a very good control / match for scATAC and so removed them from our provided references.  If you provide a custom reference with your own dnase.bed then it should run without any trouble.
