### ISSUE TITLE
Usage of multiple h5 files to create Seurat object

### ISSUE THREAD

**Issue by kaanokay** [10XGenomics/cellranger#137]
Hi,

I have .h5 files for different samples. For example, sample1.h5, sample2.h5, and sample3.h5. I want to create a Seurat object from these three h5 files. I know Read10X_h5() function can read h5 files, but I want to put all three samples into a Seurat object. How can I do this? Can I merge three h5 files to create only one h5 file and then generate Seurat object ? Or Can I read each h5 file seperately with Read10X_h5() function, and then generate separate Seurat objects, eventually combine these Seurat objects into one Seurat object?

I'm confused about that. Can you help me about this?

Thank you for your interest.
Best regards.

**Comment by dialvarezs** [comment]
Seurat can merge objects, check this vignette: https://satijalab.org/seurat/articles/merge_vignette.html
If you have more questions maybe you could ask  in https://www.biostars.org

**Comment by kaanokay** [comment]
@dialvarezs thank you for your quick response.

Bw.
