### ISSUE TITLE
Rerun `cellranger multi` with different parameters without having to rerun the full alignment ? 

### ISSUE THREAD

**Issue by plijnzaad** [10XGenomics/cellranger#140]
In a recent cellplex run of ours, the default `min-assignment-confidence` parameter of 0.9 was too stringent.  I have been in contact with technical support about this but apparently you really have to do a full `cellranger multi` rerun when choosing a different parameter; it can't be done with  (e.g.) `cellranger reanalyze`.  It would be very helpful if this were possible,  avoiding the alignment steps, saving much time (and diskspace) and allowing easier exploration of the data. Support know about this, but I had forgotten about this github repo so I thought I'd enter it here too, also to see if other users would benefit from this.

**Comment by evolvedmicrobe** [comment]
Thanks for this feedback @plijnzaad!  We're having internal conversations about this, and may have future improvements addressing this.
