### ISSUE TITLE
Does cellranger support analyzing sequences obtained from other companies?

### ISSUE THREAD

**Issue by rocketeer1998** [10XGenomics/cellranger#143]
I'm downloading a .fastq file from NCBI which were sequenced by BGI-SEQ 500. So I'm wondering whether this .fastq file can be imported as a `cellranger count` input?

Thanks for your patience to answer this general question!

**Comment by evolvedmicrobe** [comment]
Hi @rocketeer1998,

Cell Ranger can only be used to analyze 10X data, but it should work with any sequencing technology that produces conforming FASTQs.

Cheers,
Nigel
