### ISSUE TITLE
cellranger testrun --id=tiny show KeyError: 'pca'

### ISSUE THREAD

**Issue by levinit** [10XGenomics/cellranger#144]
detail
> md5sum cellranger-6.1.2.tar.gz 
> 310d4453acacf0eec52e76aded14024c  cellranger-6.1.2.tar.gz

```shell
tar xzvf cellranger-6.1.2.tar.gz 
cd cellranger-6.1.2 
```
then
> $ cellranger testrun --id=tiny
> Martian Runtime - v4.0.6
> 2021-11-19 10:31:10 [runtime] Reattaching in local mode.
> Serving UI at http://c01:41168?auth=ogEdyEX2rxZTw9U1V-vLxPLf1JHMYviu9f3L3Y5juSU
>
> 2021-11-19 10:31:12 [runtime] (reset-partial)   ID.tiny.SC_RNA_COUNTER_CS.SC_MULTI_CORE.MULTI_REPORTER.SUMMARIZE_REPORTS.fork0.chnk0
> 2021-11-19 10:31:12 [runtime] Found orphaned local stage: ID.tiny.SC_RNA_COUNTER_CS.SC_MULTI_CORE.MULTI_REPORTER.SUMMARIZE_REPORTS
> 2021-11-19 10:31:14 [runtime] (split_complete)  ID.tiny.SC_RNA_COUNTER_CS.SC_MULTI_CORE.MULTI_REPORTER.SUMMARIZE_REPORTS
> 2021-11-19 10:31:14 [runtime] (run:local)       ID.tiny.SC_RNA_COUNTER_CS.SC_MULTI_CORE.MULTI_REPORTER.SUMMARIZE_REPORTS.fork0.chnk0.main
> 2021-11-19 10:31:20 [runtime] (failed)          ID.tiny.SC_RNA_COUNTER_CS.SC_MULTI_CORE.MULTI_REPORTER.SUMMARIZE_REPORTS
>
> [error] Pipestance failed. Error log at:
> tiny/SC_RNA_COUNTER_CS/SC_MULTI_CORE/MULTI_REPORTER/SUMMARIZE_REPORTS/fork0/chnk0-u6578970c70/_errors
>
> Log message:
> Traceback (most recent call last):
>   File "/share/home/lmy/cellranger-6.1.2/external/martian/adapters/python/martian_shell.py", line 662, in _main
>     stage.main()
>   File "/share/home/lmy/cellranger-6.1.2/external/martian/adapters/python/martian_shell.py", line 621, in main
>     self._run(lambda: self._module.main(args, outs))
>   File "/share/home/lmy/cellranger-6.1.2/external/martian/adapters/python/martian_shell.py", line 592, in _run
>     cmd()
>   File "/share/home/lmy/cellranger-6.1.2/external/martian/adapters/python/martian_shell.py", line 621, in <lambda>
>     self._run(lambda: self._module.main(args, outs))
>   File "/share/home/lmy/cellranger-6.1.2/mro/rna/stages/counter/summarize_reports/__init__.py", line 72, in main
>     sample_data = cr_webshim.load_sample_data(sample_properties, sample_data_paths)
>   File "/share/home/lmy/cellranger-6.1.2/lib/python/cellranger/webshim/common.py", line 748, in load_sample_data
>     return SampleData(sample_properties, sample_data_paths, plot_preprocess)
>   File "/share/home/lmy/cellranger-6.1.2/lib/python/cellranger/webshim/data.py", line 89, in __init__
>     self.analyses, self.original_cluster_sizes = load_analyses(
>   File "/share/home/lmy/cellranger-6.1.2/lib/python/cellranger/webshim/data.py", line 305, in load_analyses
>     analyses = [cr_sg_analysis.SingleGenomeAnalysis.load_default_format(base_dir, "pca")]
>   File "/share/home/lmy/cellranger-6.1.2/lib/python/cellranger/analysis/singlegenome.py", line 242, in load_default_format
>     return SingleGenomeAnalysis.load_h5(h5_file_path, method)
>   File "/share/home/lmy/cellranger-6.1.2/lib/python/cellranger/analysis/singlegenome.py", line 173, in load_h5
>     group = f.root._v_groups[grp]
>   File "/share/home/lmy/cellranger-6.1.2/external/anaconda/lib/python3.8/site-packages/tables/misc/proxydict.py", line 33, in __getitem__
>     raise KeyError(key)
> KeyError: 'pca'
>
>
> Waiting 6 seconds for UI to do final refresh.
> Pipestance failed. Use --noexit option to keep UI running after failure.
>
> 2021-11-19 10:31:26 Shutting down.

**Comment by evolvedmicrobe** [comment]
For quick help on this, please an email to support@10xgenomics.com referencing this issue.

**Comment by levinit** [comment]
solved it.
run testrun in a dir mounted via glusterfs , this problem occur, now I run it in a dir mounted via NFS, it works.
