### ISSUE TITLE
cellranger count error: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by chocokuma** [10XGenomics/cellranger#147]
Hi
I am trying to use Cellranger count by submitting the jobs to some nodes, but segmentation faults occur.
I think the nodes have enough specs
Can I get some help with this?
Thank you :)

```
#!/usr/bin/bash 
#SBATCH -N1 -n1 -c16 -o /dev/null --mem-per-cpu 15G 
exec &> /home/users/myname/log/count/count_srr15103231.log 

 cellranger count --id=run_count_srr15103231 --fastqs=/home/users/myname/srr15103231 --transcriptome=/home/users/myname/sequence/reference/refdata-gex-GRCh38-2020-A
```

```
[error] Pipestance failed. Error log at:
run_count_srr15103231/SC_RNA_COUNTER_CS/SC_MULTI_CORE/MULTI_GEM_WELL_PROCESSOR/COUNT_GEM_WELL_PROCESSOR/_BASIC_SC_RNA_COUNTER/_MATRIX_COMPUTER/ALIGN_AND_COUNT/fork0/chnk07-u1380ee511a/_errors

Log message:
Job failed in stage code

signal: segmentation fault (core dumped)


Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

2022-01-24 16:13:16 Shutting down.
```

**Comment by evolvedmicrobe** [comment]
Hmm... seg faults are unexpected. To diagnose, please upload the debug info as described here: 

https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/troubleshooting

and reach out to support@10xgenomics.com so we can assist.

**Comment by chocokuma** [comment]
Deleting and re-downloading the reference genome file worked!
(It seems that the problem was caused by inappropriate unzipping of the genome file.)
Thank you!
