### ISSUE TITLE
"Reference contains a contig longer than 536.8Mb (2^29 bp),Please split this contig."

### ISSUE THREAD

**Issue by mihuzx** [10XGenomics/cellranger#148]
Hi,

Do you know how to solve this problem for huge genome? Or do you have any suggestions about how to split the genome and annotation at the same time?

Thanks
Xuan

**Comment by evolvedmicrobe** [comment]
I am not sure which product or version produced this error, are you using `cellranger arc`?

**Comment by mihuzx** [comment]
> 

Sorry for the confusion.

I was tried to build the index for wheat genome(17Gb) with cellranger-atac. and the code I used is `cellranger-atac mkref --config=./wheat_iwgsc_v2.1_config_v2.txt` 

The error message is below:
```
Computing hash of genes GTF file...
...done

...done



mkref has FAILED
mkref has constructed an invalid reference, which is a bug.
Error: The supplied reference path /scratch/xz24199/GenomeRef/wheat_iwgsc/wheat_iwgsc_v2_cellranger_v2 is not a valid 10x reference on machine ra7-1.compute.lan:
Reference contains a contig longer than 536.8Mb (2^29 bp), which is not supported due to limitations of the .bai format. Please split this contig.
Please make sure that you have downloaded the correct 10x reference or generated a custom reference using `mkref`. Cell Ranger ATAC pipelines are compatible with Cell Ranger ATAC 2.0 or Cell Ranger ARC 1.0+ references. Cell Ranger ARC pipelines are compatible with a Cell Ranger ARC 1.0+ reference
Please contact support@10xgenomics.com.

```

Thank you for you time.
Xuan

**Comment by brettolsen** [comment]
Apologies.  This is a known issue with extremely large contigs caused by the limitations of our current indexing scheme.  Your best path forward is to split the offending contigs to be below the limit.  I would suggest splitting in regions with low mappability (e.g., centromeres) or far from annotated genes.  I'm sorry, but we don't currently offer any tools to assist with this.

**Comment by IrinaVKuznetsova** [comment]
Hi Xuan, 

Have you figure out how to split each chromosome into smaller, without hitting gene locations?


 

> > 
> 
> Sorry for the confusion.
> 
> I was tried to build the index for wheat genome(17Gb) with cellranger-atac. and the code I used is `cellranger-atac mkref --config=./wheat_iwgsc_v2.1_config_v2.txt`
> 
> The error message is below:
> 
> ```
> Computing hash of genes GTF file...
> ...done
> 
> ...done
> 
> 
> 
> mkref has FAILED
> mkref has constructed an invalid reference, which is a bug.
> Error: The supplied reference path /scratch/xz24199/GenomeRef/wheat_iwgsc/wheat_iwgsc_v2_cellranger_v2 is not a valid 10x reference on machine ra7-1.compute.lan:
> Reference contains a contig longer than 536.8Mb (2^29 bp), which is not supported due to limitations of the .bai format. Please split this contig.
> Please make sure that you have downloaded the correct 10x reference or generated a custom reference using `mkref`. Cell Ranger ATAC pipelines are compatible with Cell Ranger ATAC 2.0 or Cell Ranger ARC 1.0+ references. Cell Ranger ARC pipelines are compatible with a Cell Ranger ARC 1.0+ reference
> Please contact support@10xgenomics.com.
> ```
> 
> Thank you for you time. Xuan
