### ISSUE TITLE
how to download fastqs from https://support.10xgenomics.com/single-cell-gene-expression/datasets

### ISSUE THREAD

**Issue by 2236529177** [10XGenomics/cellranger#15]
hi, there, thank you in advance, I want ot know how to downlaod fastqs from https://support.10xgenomics.com/single-cell-gene-expression/datasets, thanks

**Comment by namisaghaei** [comment]
Click on the dataset you need, then under ```view summary``` click ```show batch download instructions```. You'll see curl commands for all of the files in the dataset.
