### ISSUE TITLE
Filtering out unspliced UMIs

### ISSUE THREAD

**Issue by Chhiring-Lama** [10XGenomics/cellranger#153]
Hi, 
I want to run cellranger count on gene expression data we have, but only want to capture the spliced transcript. I understand the not using `include-introns` we simply exclude the introns read. Is there anyway to modify/add arguments to filter out unspliced transcripts?

**Comment by evolvedmicrobe** [comment]
Hmm, that's pretty advanced, one problem is that it's generally not possible to know if a transcript is fully spliced or not from short read data, as you only observe a portion of the molecule, so a read that completely overlaps an exon could come from a spliced transcript or an unspliced one.

If for some reason you wanted to include only molecules that were definitively spliced, you could generate a reference genome that only included the "splice junctions" so reads that didn't align to these were removed.  Perhaps the folks over at the STAR aligner github have some other ideas (that's the aligner cell ranger uses, https://github.com/alexdobin/STAR)
