### ISSUE TITLE
Feature MEX file output incorrect

### ISSUE THREAD

**Issue by lmogil** [10XGenomics/cellranger#155]
I recently upgraded to cellranger version 6.1. and discovered that the feature file contains quotations around each row. This posses issues for post processing. I have resolved this manually but is there a way to get this addressed in the software package?
Example of a line in the file:
"ENSG00000223972.5      DDX11L1 Gene Expression"

**Comment by evolvedmicrobe** [comment]
Which feature file are you referring to?

**Comment by lmogil** [comment]
in the filtered MEX output. the file is called feature.tsv.gz. its one of three files in for analysis along with barcodes.tsv.gz and matrix.mtx.gz

**Comment by evolvedmicrobe** [comment]
I just check a few of our example datasets and didn't see the quotes in that file when I unzipped it, do you observe this with any of our example datasets?
