### ISSUE TITLE
cellranger vdj   run error

### ISSUE THREAD

**Issue by yanpinlu** [10XGenomics/cellranger#156]
When I use cellranger vdj, the following problem occurs, what is the reason for the following problem with individual data, the original data is complete

[error] Pipestance failed. Error log at:
count3634/SC_VDJ_ASSEMBLER_CS/SC_MULTI_CORE/MULTI_GEM_WELL_PROCESSOR/VDJ_T_GEM_WELL_PROCESSOR/SC_VDJ_CONTIG_ASSEM9547af8f/_errors
Log message:
Input FASTQ file ended prematurely: file: "/home/lu_yanping/data/data1/TCR/gdfastq/SRR11813634_S1_L001_R1_001.fas
Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

**Comment by evolvedmicrobe** [comment]
Please contact support@10xgenomics.com for help with this issue, it's likely that FASTQ file was corrupt
