### ISSUE TITLE
cellranger process single-end scRNAseq

### ISSUE THREAD

**Issue by BioEpi** [10XGenomics/cellranger#179]
Hello,
    I am just wondering whether cellranger count can process single-end scRNA-seq. This paper said that they used cellranger to process single-end scRNA-seq(https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129519).
`The Cell Ranger 2.0.1 pipeline (10X Genomics) was used to align reads from RNA-seq to the GRCh38 human reference genome and produce the associated cell by gene count matrix.`

Thanks in advance.

**Comment by evolvedmicrobe** [comment]
Cell Ranger does not process single end data, and that paper seems to have used paired end data 

`Single-cell RNA-Seq libraries were prepared with the Chromium™ Single Cell 3’ Library & Gel Bead Kit v2 (10x Genomics, PN-120237). Libraries from different samples were pooled based on molar concentrations and sequenced on a NextSeq 500 instrument (Illumina) with 26 bases for read 1, 57 bases for read 2 and 8 bases for Index 1`

Which likely explains how they still managed to use Cell Ranger.
