### ISSUE TITLE
How to get unmapped raw PAIRED FASTQ reads files by running CellRanger

### ISSUE THREAD

**Issue by SeadonXing** [10XGenomics/cellranger#19]
Dear Paul Ryvkin  : 
   I want to get the unmapped reads when after mapping to the genomeA by using cellragner. And then use the unmapped paired reads(with UMI) to map to genomeB. For full length without UNI based protocol this process is easy to handle. But for UMI based protocol I have no ideal ideas. What I can do I think is  : 
(1) samtools view -f 4 possorted_genome_bam.bam > unmapped.bam
(2) bam2fastq tools to convert unmapped.bam to unmapped_R2.fastq (V2 3` chemistry)
(3) select the reads in raw_R1.fastq file(with UMI) to paired with the reads in unmapped_R2.fastq so I can get the new unmapped pair-end fastq files named unmapped_R1.fastq and unmapped_R2.fastq (this step I don't know which tools can used ???) 
(4) finally , rerun cellranger with the unmapped data to the genomeB

So any hints for me to achieved my aims.  Can cellranger output the unmapped pired fastq files straightly ?
Thank you for replay.

Best
Seadon

**Comment by worsteggs** [comment]
Hello SeadonXing：
Did you solve your problem? I am having the same problem.

Best
Eggs

**Comment by evolvedmicrobe** [comment]
Hi @SeadonXing, Cell Ranger does not output any FASTQs, however the BAM file you mentioned does include a `CB` and `UB` tag which will allow you to obtain the barcode and UMI associated with each read without going back to the original FASTQs.  See:

https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam
