### ISSUE TITLE
ATAC- Cell Ranger ARC

### ISSUE THREAD

**Issue by jiangzh-coder** [10XGenomics/cellranger#193]
Hi，

If i analyzed10xgenomics ATAC- Cell Ranger ARC dataset，can i do following?

1. For ATAC- Cell Ranger ARC-count， can i use sra datasets（scRNAseq+scATACseq), transformed them into FASTQ files by using fasterq-dump or parallel-fastq-dump, then rename them? 
https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/what-is-cell-ranger-arc
https://www.jianshu.com/p/36dc29ae0ed9
https://kb.10xgenomics.com/hc/en-us/articles/360061165691-Can-I-analyze-only-the-ATAC-data-from-my-single-cell-multiome-experiment-

2. For ATAC- Cell Ranger ARC-count， how can i index reference genome？
https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/advanced/references
https://support.10xgenomics.com/single-cell-atac/software/release-notes/references
https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/tutorial/mkref

thanks and best wishes
Jiang

**Comment by evolvedmicrobe** [comment]
Hi, please reach out to support@10xgenomics.com who will be able to help you with this.
