### ISSUE TITLE
urgent: cellranger-arc questions

### ISSUE THREAD

**Issue by jiangzh-coder** [10XGenomics/cellranger#194]
Hi, 

I tried to analyze public GEO dataset. I selected 1 sample for cellranger upstream analysis.
I divided sample into 2 batches (batch1: GEX, SRR##### and ATAC, SRR#####; batch2: 
GEX, SRR##### and ATAC, SRR#####). Firstly, i used attached code and cellranger-arc to 
analyze batch1; then secondly, i used same attached code and cellranger-arc to 
analyze batch2. Finally i used cellranger-arc aggr to combine results together for 1 sample. 

I have 3 questions:

1) From results1, my results files are a little bit larger than results from GEO dataset. Is my analysis correct?

2) In the combines results, the file "per_barcode_metrics.csv" which i need in the downstream analysis is
missing. I found them in the seperate folders which belong to batch1 or batch2. How can i use 
cellranger-arc aggr to merge them together?

3) In thsi paper, the auther used following methods to reanalyze data: " 
Post-sequencing, FASTQ readouts for both single-cell gene expression (scGEX)
and scATAC were input into the CellRanger pipeline (v.2.0.0) to perform sequence
alignment and peak calling (for ATAC) and assemble the counts data. Finally,
joint cell calling filtered the cells containing both scGEX and peak information.".

How can i do "joint cell calling"?

best wishes
Jiang

**Comment by jiangzh-coder** [comment]
Hi, 

As i read from following website, 
https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/using/fastq-input#gex_rightname
https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/using/count

i should put 2 batches into 1 folder as attached figure. 
So the libraries CSV file (for cellranger-arc count) "(MKFASTQ_ID)HFL(GEX or ATAC)/outs/fastq_path/test_sample1" folder. 
I should finally run 4 batches for 1 sample together for 1 time cellranger-arc count. Correct? 

best wishes
Jiang

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
