### ISSUE TITLE
spaceranger mapping problem

### ISSUE THREAD

**Issue by fenghuijian** [10XGenomics/cellranger#198]
spaceranger 
Why has the progress not been successfully changed, it's been running for 11 hours
![图片](https://user-images.githubusercontent.com/43702564/210292559-075eaed4-4d97-45e5-b95b-bec59cc23eb1.png)

**Comment by evolvedmicrobe** [comment]
That's indeed a lot longer than it should possibly take, please contact support@10xgenomics.com who can provide further assistance to unstick this.
