### ISSUE TITLE
How to run cellranger on Apple M1/2 machines

### ISSUE THREAD

**Issue by RenGroup** [10XGenomics/cellranger#199]
I tried to run cellranger 7.1.0 on an Apple M2 machine, but after I unzipped the tarball, running "cellranger testrun --id=tiny" gave me "zsh: exec format error: cellranger". I tried running in another terminal opened with Rosetta, but got the same result. I guess this might be caused by the ARM architecture of the chip (correct me if I'm wrong). Is there any way that I can run cellranger on an Apple M1/M2 machine?

**Comment by Carmen-Carmen** [comment]
Have you tried to build the cell ranger binaries on your arm device?

**Comment by adam-azarchs** [comment]
`cellranger` requires a 64-bit x86 CPU with at least 64GB of memory.  Please refer to the [cellranger system requirements](https://www.10xgenomics.com/support/software/cell-ranger/downloads/cr-system-requirements) on the support page.  It may be possible to run in an emulator, though that would be an unsupported setup and it would likely be painfully slow.  If you don't have access to an x86 CPU, our usual recommendation would be to use [cloud analysis](https://www.10xgenomics.com/products/cloud-analysis).

Even if you have an M2 machine with sufficient memory, it is not possible to recompile cellranger for ARM - we've tried, internally, for the convenience of our own developers who want to use Apple hardware for development.  While it is possible for some components of the product, it's proven prohibitively difficult to find all of the places in our own code or in our dependencies where something is assuming x64 as the architecture.
