### ISSUE TITLE
How to analysis the single cell infected by the virus by cellranger ?

### ISSUE THREAD

**Issue by SeadonXing** [10XGenomics/cellranger#20]
Hi : 
    I'd like to use cellranger to analysis my 10X single cell transcript data of a sample infected by a virus.  I want to quantify each of the virus genes expression level within each of cells. I have two strategies below : 
 (1)  First map to Human Reference Genome and then the reads unmapped were mapped to the virus reference genome.  The most difficult things is how to get umapped paired raw reads fastq files after running cellranger. (Even The second straight is better and easy to do. I still want to know how to get unmapped paired reads by cellranger :)  )
(2) Add the virus genome to Human reference genome and add the annotation of virus GTF files to human annotation files too.  Then analysis together with cellranger. 

Which one is bettter for my questions , and do you have some advices and more better straight to do that ???

Hope for reply
Best
Seadon

**Comment by evolvedmicrobe** [comment]
Hi @SeadonXing,

Please feel free to send question like this to support@10xgenomics.com in the future for a much faster response.  My recommendation for this would be to go with your option (2), as this allows you to map all reads at once and in the (unlikely) even the virus genome overlaps at all with the human genome, you'll avoid ambiguous mapping issues.
