### ISSUE TITLE
CellRanger3 vs CellRanger5 deviating results for annotation of TRA and TRB in VDJ

### ISSUE THREAD

**Issue by Close-your-eyes** [10XGenomics/cellranger#200]
Dear all,

it happened to me that we mapped the same data 10X VDJ data from human T cells with CellRanger3 and CellRanger5 to a hg38 reference.
I noticed that in CellRanger5 much less cells are annotated with TR chains. So, filtering must have become stricter. Okay.

Apart from that, some cells (barcodes) have been annotated with completely different CDR3s (TRA and TRB) and accordingly with different underlying contig sequences.

I am referring to data from filtered_contig_annotations.csv and filtered_contig.fasta.

Is this known? Is it expected? How can that be explained?

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
