### ISSUE TITLE
Obtain fastQ file from .bam files

### ISSUE THREAD

**Issue by pmarzano97** [10XGenomics/cellranger#201]
Hello world!
I'm trying to process public .bam files to obtain fastQ files.

I've downloaded the files from the ENA browser (for example https://www.ebi.ac.uk/ena/browser/view/ERR3804256), and I've obtained a file named "WSSS8062674.bam".
Then, I launched on the terminal the command "cellranger bamtofastq" but this error came up:
"_bamtofastq v1.4.1
WARNING: no @RG (read group) headers found in BAM file. Splitting data by the GEM well marked in the corrected barcode tag.
Reads without a corrected barcode will not appear in output FASTQs
Unrecognized 10x BAM file._"

How can I proceed with the processing? Is there a way to fix this issue? Do I need to rename the file .bam or something different that I can do? My goal is to convert it to fastQ to do the CellRanger count command and obtain a file on which I can work.
The authors processed the files I would like to analyze with CellRanger 2.1.0, but did not upload the fastQ files, only the .bam ones.

Thanks all!

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
