### ISSUE TITLE
Cellranger count creating an empty matrix.mtx after adding 'N' and '#' to R1 UMI and quality respectively to account for 9bp UMI.

### ISSUE THREAD

**Issue by JHorder** [10XGenomics/cellranger#202]
Hi!

I am currently analysing public scRNA-seq datasets from raw reads.

For a public dataset, the R1 read length is 25. The library was generated with an older version of the chemistry. This throws an error in cellranger as the read length is too short.

To handle this, 'N' were added to the end of the R1 reads as described in this [10XGenomics page](https://kb.10xgenomics.com/hc/en-us/articles/360053937392-How-to-resolve-this-error-We-detected-a-mixture-of-different-R1-lengths-) via a simple `sed` command.

This [paper](https://academic.oup.com/gigascience/article/doi/10.1093/gigascience/giac001/6515741?login=true#328524523) describes adding 'A' to the UMI to handle this.

A subsequent error was raised with the message `Sequence and quality length mismatch`. This was dealt with by adding an '#' to the quality score line to coincide with the 'N' of the sequence.

A R1 read length of 26 was achieved.

Example:

Prior to UMI length adjustment:

    @ST-K00127:336:HVYF2BBXX:1:1101:23744:1244 1:N:0:GAGNATNT
    GGGCACTTCTTGNATTTCTGTTTTC
    +
    AAFFFJJJJJJJ#FFAJJFJAJJFJ

Post UMI length adjustment:

    @ST-K00127:336:HVYF2BBXX:1:1101:23744:1244 1:N:0:GAGNATNT
    GGGCACTTCTTGNATTTCTGTTTTCN
    +
    AAFFFJJJJJJJ#FFAJJFJAJJFJ#

Cellranger count ran and completed with a success message.

However, it was noticed that the filtered_features_bc_matrix matrix.mtx.gz and the raw_features_bc_matrix matrix.mtx.gz files are empty bar the header:

Example:

    %%MatrixMarket matrix coordinate integer general
    %metadata_json: {"software_version": "Cell Ranger 4", "format_version": 2}
    36601 551223 0

I'm assuming this is due to the handling of the UMI. Is there a way to resolve this?

Thanks!

    $ cellranger --version
    cellranger cellranger-7.0.1

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
