### ISSUE TITLE
cellranger multi only assigning one CMO

### ISSUE THREAD

**Issue by cap76** [10XGenomics/cellranger#205]
I have a potential issue when running cellranger multi (cellranger v7.0.0) for a multiplexed dataset. I'm sure I'm making a mistake somewhere but can't figure it out. Essentially when I run cellranger muli it only seems to assign a single cmo to the datasets. 

I am running: cellranger multi --id OutputFolder --csv Sample_template.csv

where Sample_template looks like:

[gene-expression]
reference,/path/t/genome/

[libraries]
fastq_id,fastqs,lanes,feature_types
FASTQID,/path/to/fastqs/,any,Gene Expression
FASTQID,/path/to/fastqs,any,Multiplexing Capture

[samples]
sample_id,cmo_ids,description
Sample1,CMO310,Sample1
Sample2,CMO309,Sample2

This seems to run fine and the job completes. When I look in the output folder OutputFolder/outs/per_sample_outs/ I see two folders: Sample1 and Sample2. However, only one of these folders appears to have anything mapped e.g., in Sample2/count/sample_filtered_feature_bc_matrix the barcodes.tsv.gz file is there and has data in it, but if I look at Sample1/count/sample_filtered_feature_bc_matrix, the barcodes.tsv.gz file is there but an empty file. If I look in outs/multi/multiplexing_analysis/tag_calls_summary.csv I see that cells are only being assigned to CMO309

Category,num_cells,pct_cells,median_umis,stddev_umis
No tag molecules,4,0.0,None,None
No tag assigned,649,6.8,None,None
1 tag assigned,8921,93.2,None,None
More than 1 tag assigned,0,0.0,None,None
CMO309,8921,93.2,2807.0,1005.2

I thought perhaps one sample had simply failed, however, I have the exact same thing happen with a completely different sample and if I open the Sample2/web_summary.html I get a warning "Tag(s) CMO310 were identified as contaminants ... You should check if your input CSV contained the right list of tags used."

So it looks like CMP309 and CMO310 are being recognised somewhere in the run, but only CM309 is being assigned. Any suggestions about where this might be arising or possible pointers about how to debug would be greatly appreciated.

**Comment by Boroviak-Lab** [comment]
Adding a follow up question that may help me figure things out: in my dataset which has the form:

ID_GEX_I1.fastq.gz
ID_GEX_I2.fastq.gz
ID_GEX_R1.fastq.gz
ID_GEX_R2.fastq.gz

ID_CMX_I1.fastq.gz
ID_CMX_I2.fastq.gz
ID_CMX_R1.fastq.gz
ID_CMX_R2.fastq.gz

In which data file *should* sequenced feature barcodes be? Would this be the CMX_R1.fastq.gz/ R2.fastq.gz files?

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
