### ISSUE TITLE
how to solve SGE mode error

### ISSUE THREAD

**Issue by felixlee0608** [10XGenomics/cellranger#206]
File "/nfs1/public2/User/felix/Software/cellranger-7.1.0/lib/python/cellranger/constants.py", line 170, in aggr_files
    paths: list[str]
TypeError: 'type' object is not subscriptable

```bash
cellranger count --id=xx_sge \
	--jobmode=sge \
	--maxjobs=20 \
	--jobinterval=20 
```

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
