### ISSUE TITLE
Error: testrun

### ISSUE THREAD

**Issue by lijie0328** [10XGenomics/cellranger#21]
It's my first time to use the version 2.2.0 of cellranger and I did try running cellranger testrun. But I got some error message.

cellranger testrun --id=tiny

 "errors": [
 "lstat */MERGE_CLUSTERS/fork0/join-u211eda6f1f/files/clusters_csv: no such file or directory",
 "lstat */MERGE_CLUSTERS/fork0/join-u211eda6f1f/files/clusters_h5.h5: no such file or directory",
 "lstat */PREPROCESS_MATRIX/fork0/join-u211eda6ed0/files/preprocessed_matrix_h5.h5: no such file or directory",
 "lstat */RUN_DIFFERENTIAL_EXPRESSION/fork0/join-u211eda6f3e/files/diffexp_csv: no such file or directory",
........

**Comment by evolvedmicrobe** [comment]
Hi @lijie0328, for fast responses to issues like this, please contact support@10xgenomics.com .
