### ISSUE TITLE
Selecting primary alignment in duplicate reads

### ISSUE THREAD

**Issue by kwcurrin** [10XGenomics/cellranger#213]
Hello,

In cellranger-arc for ATAC-seq, how is the primary alignment chosen out of a group of duplicates? Is it random? Or is it based on base quality like picard or mapping quality like samtools? Or some other method? Where could I find relevant code in the cellranger-arc instllation?

Thanks,

Kevin

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
