### ISSUE TITLE
Dehash fastq files

### ISSUE THREAD

**Issue by royfrancis** [10XGenomics/cellranger#214]
I have fastq files from a hashed 10X VDJ library that looks like this:

```
PBMC_1_3_1_TCR_S5_L001_I1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_R2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_R1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_I2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_I1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_R2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_R1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_I2_001.fastq.gz
```

This is one library that has 3 samples hashed and pooled together. Is it possible to dehash these fastq files into three separate fastq files by sample? I am looking for dehashing at fastq level and not at count level.

**Comment by evolvedmicrobe** [comment]
This is our [current recommended workflow](https://www.10xgenomics.com/resources/analysis-guides/demultiplexing-and-analyzing-5%E2%80%99-immune-profiling-libraries-pooled-with-hashtags) for this.
