### ISSUE TITLE
FASTQ file names with _001

### ISSUE THREAD

**Issue by Serena-Fang** [10XGenomics/cellranger#222]
On the website, it indicates that Cell Ranger requires the FASTQ files ending with _001. 
https://kb.10xgenomics.com/hc/en-us/articles/115003802691-How-do-I-prepare-Sequence-Read-Archive-SRA-data-from-NCBI-for-Cell-Ranger-

However, the files we got contain other suffixes than _001, eg. 002, 003, etc. Will Cell Ranger see all those additional files, or they all need to end with ‘001’ as the website seems to be suggesting?

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
