### ISSUE TITLE
Using CellRanger for other UMI-based Single-Cell Platforms

### ISSUE THREAD

**Issue by hkarakurt8742** [10XGenomics/cellranger#223]
Hello,
I am using CellRanger for the analysis of 10X Chromium based public datasets for a study but one of the studies are actually sequenced using Singleron GEXSCOPE and as I know this platform also uses UMI (I am not sure if it is full length transcript or 3' or 5' end).
Is it possible to use such datasets with CellRanger?

Thank you in advance.

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
