### ISSUE TITLE
Duplicate FASTQs found  when use cellranger count for Feature Barcode Analysis

### ISSUE THREAD

**Issue by semir2** [10XGenomics/cellranger#225]
Hi, thank you for great tool for single cell Feature Barcode Analysis,.
Now, I download [fastq files](https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR15904933&display=data-access) from ncbi with sra formats, which combined  gene expression fastq file, vdj  fastq file and antigen Capture fastq file for only one fastq file , and it difficult to split the fastq file, so I analysised single cell gene expression and feature barcode with  this fastq file by cellranger count or multi, hower cellranger could not work with error of  'Duplicate FASTQs found between Sample'.

Could you help me pleases? How can I sovle this problem?

Bests

**Comment by evolvedmicrobe** [comment]
Please contact support@10xgenomics.com - you likely will need to split up your FASTQ files into separate ones for each library.

**Comment by semir2** [comment]
ok thanks
