### ISSUE TITLE
Brcode Rank Plot y-axis scale

### ISSUE THREAD

**Issue by MartaBenegas** [10XGenomics/cellranger#227]
Hi! 

Sorry if it's a dumb question, but I don't understand how the y-axis values are calculated in the Barcode Rank Plot. I've only encountered one explanation [on this webpage](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/barcode-rank-plot). Here it says that the y-axis is on a logarithmic scale, but I would like to know how is it calculated. 

For example, with my dataset I obtained the following result:
![image](https://github.com/10XGenomics/cellranger/assets/57805802/b28ec434-9882-4019-b335-fc608e4004aa)

If I calculate different logarithms of the median UMI counts per cell, the numbers are really far from 10k or even 1000, which is what I would expect since I assume that the cells in the final count table should fall in that region:

log10(4957) = 3'695...
loge(4957) = 8'5...
log2(4957) = 12'275...

Thank you in advance!

**Comment by evolvedmicrobe** [comment]
The scale is logarithmic in the sense that there is an order of magnitude difference between the tick marks on the axes, e.g. 1/10/100/1000/10K/etc.  However, the values displayed are not log transformed, they are just the UMI counts, so the 4957 median value is between the 1K and 10K tick marks.
