### ISSUE TITLE
spaceranger mkfastq [error] You must specify either a samplesheet or CSV file.

### ISSUE THREAD

**Issue by feasiblee** [10XGenomics/cellranger#229]
spaceranger mkfastq --id=tiny-bcl \
> --run=/public3/home/sc73251/spaceranger_tutorial/mkfastq/spaceranger-tiny-bcl-1.0.0\
> --csv=spaceranger-tiny-bcl-simple-1.0.0.csv

[error] You must specify either a samplesheet or CSV file.

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
