### ISSUE TITLE
What is needed from ./external/?

### ISSUE THREAD

**Issue by nick-youngblut** [10XGenomics/cellranger#231]
Since the `./external/` directory in `cellranger-7.1.0` is ~1.5 Gb, I would like to exclude it from my custom Cell Ranger Docker container. However, if one runs `cellranger count` without the `./external/` directory, then one gets the error:

```bash
       Caused by: Failed to run mrg
        Caused by: No such file or directory (os error 2)
```

What is actually *required* in the `./external/` directory for running of `cellranger count` (and other subcommands)? 
Maybe a fork could be created of cellranger that is a minimal version that is optimized for Docker containers (e.g., a `cellranger-slim` version)? The `cellranger-7.1.0` codebase is nearly 2 Gb when uncompressed.

Maybe `anaconda` can be replaced with [micromamba](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html)?

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.

**Comment by nick-youngblut** [comment]
> GitHub Issues are not monitored by our support team

Thanks @elehnert10x for the info. It might be helpful to put that info in the issue template for this repo.

**Comment by elehnert10x** [comment]
Thank you for your understanding. We will be making that more clear - we wanted to respond and provide recent inquiries a path forward before making those changes.
