### ISSUE TITLE
cellranger atac count (force cells issue)

### ISSUE THREAD

**Issue by samandmac** [10XGenomics/cellranger#232]
Hi there,

I've recently run cellranger-atac count, but for some reason in one of the samples it is using --force-cells even though I did not specify to in the code (see below)

`cellranger-atac count --id=sample --reference=refdata-cellranger-arc-mm10-2020-A-2.0.0 --fastqs=fastq/sample --sample=sample --localcores=24 --localmem=64`

Perhaps a misunderstanding on my part, but why does it automatically use force cells? And will this be affecting my results, because the results for this sample end up with estimated cells of ~20,000 cells. 

For reference, none of the samples before or after this particular set have any issues with force cells or similar cell numbers

Thanks for any help offered!

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.

**Comment by sbombin** [comment]
Hey @samandmac, I have the same issue, Have you figure out the reason?

**Comment by abhiachoudhary** [comment]
Hi @samandmac and @sbombin, I have the same issue, has either of you figured out the reason?

**Comment by brettolsen** [comment]
The current version of cellranger-atac has a hard-coded limit of no more than 20,000 cells called due to computational reasons.  It's potentially bypassable, but you'd need to talk to support to get the patches necessary to do so, and it's not recommended; we recommend a maximum cell count of 10K for a reason.

**Comment by salamere** [comment]
> The current version of cellranger-atac has a hard-coded limit of no more than 20,000 cells called due to computational reasons. It's potentially bypassable, but you'd need to talk to support to get the patches necessary to do so, and it's not recommended; we recommend a maximum cell count of 10K for a reason.

Is there a reason for the max beyond computational?  I understand some structures might have assumed smaller numbers and there could thus be some programmatic limitations, but it's easy to rent a powerful machine for a bit and run things which are computationally intensive :)
