### ISSUE TITLE
getting more estimated number of cells

### ISSUE THREAD

**Issue by archana433** [10XGenomics/cellranger#233]
I am doing cellranger count with my one sample, and we have used same GEW well and did resequencing of the same library to increase read depth. When I am combining the fastqc files and did cell ranger counts , I am getting estimated number of cells more  than sum of the both runs. 

I have used this command- 
cellranger count --id=sample_485_merged \
     --fastqs=fastq_path/AAC7GKFHV,fastq_path/AAC2WMNHV/  \
    --transcriptome=/scratch/tmp/vermaa/hg38/  \
    --sample=sample_485,sample_485 \
    --include-introns=false

1st run Estimated Number of Cells - 8,748
2nd run Estimated Number of Cells - 3,340 
merged run Estimated Number of Cells - 12,260

Is my command is right ?
Why I am not getting overlap from the same GEM well and same library?

**Comment by evolvedmicrobe** [comment]
In general, cell calling varies with sequencing depth so you shouldn't expect the same counts with both, you can learn more about our cell calling algorithm [here](https://www.10xgenomics.com/support/software/cell-ranger/algorithms-overview/cr-gex-algorithm)

**Comment by archana433** [comment]
I will reframe this question 
i am  trying 2 merge fastq files from the same sample but different sequencing runs. I now have two FASTQs files- one from the original shallow sequence and another from the new run. when I did cell ranger count , I am getting weird result. 1st run Estimated Number of Cells - 8,748. 2nd run Estimated Number of Cells - 3,340. merged run Estimated Number of Cells - 12,260

I am getting more cells, but there should be overlap because they are all from same GEM well.

cellranger count --id=sample_485_merged \ --fastqs=old_run/fastq_path/AAC7GKFHV,new_run/fastq_path/AAC2WMNHV/ \ --transcriptome=/scratch/tmp/vermaa/hg38/ \ --sample=sample_485,sample_485 \ --include-introns=false

Is my code correct? And how to resolve this problem? Why I am getting 12,260 cells while in my shallow seq it is 3,340 and another seq run - 8,748. I wouls have expecting more or less 8000-9000 cells not 12,260.

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail support@10xgenomics.com for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
