### ISSUE TITLE
aligning to a multi-reference w/ ambiguities

### ISSUE THREAD

**Issue by stanleyjs** [10XGenomics/cellranger#234]
Hello,

We have create a multi-reference that features a lot of sequence similarity in it (the multi reference is GRCh38 + Clade B, the collection of identified north american HIV variants). We expect some multi-mapping of reads to both GRCh38 loci and Clade B loci.
We have determined a set of rules for resolving alignment ambiguities.  We would like to run CR on the multi reference, parse the BAM for multi alignments, apply our rules to resolve ambiguities, and then obtain the remaining UMI counts that were previously ambiguous.

Is there a pipeline for this? We are comfortable writing our own BAM parser but not sure how best to mold this into CR's UMI assignment procedure.

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
