### ISSUE TITLE
Low alignment rate when using fastq generated from bamtofastq

### ISSUE THREAD

**Issue by malonzm1** [10XGenomics/cellranger#235]
Hi,

I had to use cellranger's bamtofastq function for some bam files. Then I used the resulting fastq files for clonotype detection (https://github.com/milaboratory/mixcr). I noticed that the alignment rate was very low (from less than 1% to around 3%). Any thoughts?

Thanks and good day.

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
