### ISSUE TITLE
CellRanger Multi Feature Barcode Error

### ISSUE THREAD

**Issue by shamer3** [10XGenomics/cellranger#237]
Hi All,

I am having some issues including a feature barcode metric within my cellranger multi pipeline. I have previously run the pipeline just fine with CMO library and GEX however now including the feature barcode (in this case cellular barcoding library information) the pipeline crashes consistently at the same point every time I run it.

![Screenshot 2023-11-29 at 15 07 56](https://github.com/10XGenomics/cellranger/assets/97258037/05455890-c6bd-43e9-9d2e-56f25fb9003e)

Im not sure whether this is an issue generated with the feature reference I have used or whether this is an issue with the pipeline trying to process, GEX, CMO and feature barcode.

Please is anyone able to help me ?

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
