### ISSUE TITLE
merge 2 sequencing run of Multiplex FRP, 1 Probe Barcode/sample

### ISSUE THREAD

**Issue by archana433** [10XGenomics/cellranger#239]
Hi,
I have Multiplex FRP, 1 Probe Barcode/sample from 2 sequencing runs. (samples are resequenced from same GEM library)
Can we run cellranger multi for 2 sequencing runs like we have option in cell ranger count?
If yes, how ?

Thank you!

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
