### ISSUE TITLE
how to filter out mouse cells to get a matrix only contained human cells from a mixture library by cellranger?

### ISSUE THREAD

**Issue by mzhoufulai** [10XGenomics/cellranger#24]
Hi,
     I am new in single-cell RNA-seq. I got a library with a mixture of human and mouse cells. The mouse cells ratio is only 2.5%. I used cellranger count to get the matrix. But the output of cellranger count is a mix of human and mouse. How I can filter out mouse cells and only get a matrix of human cells?
Thanks!

**Comment by evolvedmicrobe** [comment]
Hi,

Cell Ranger will attempt to identify which species each cell is derived from, but the approach does not work well when the ratio is far from 50:50.

My recommendation would be to use the filtered matrices directly to make your own determination.  Instructions on loading the filtered barcode matrix in either R or Python are available here:

https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices

Once loaded, genes from either genome are prefixed with the genome name (e.g. `mm10` or `hg19`) and you can sum the count of genes from each genome for each barcode to determine the species based on the relative count of mouse genes to human genes.

support@10xgenomics.com can likely provide additional follow up.

Warm wishes,
Nigel

**Comment by YuliaInn** [comment]
I have the same issue. You said we can determine the species based on the relative count of mouse genes to human genes. Is there any threshold or something for that?
thank you

**Comment by ahdee** [comment]
@evolvedmicrobe this is an older closed issue but we are having a similar issue. Can you please elaborate on your solution? For example, you mentioned, 

> Cell Ranger will attempt to identify which species each cell is derived from, but the approach does not work well when the ratio is far from 50:50.

in this case do we use the  prebuild human+mouse index?  I think on the dl page is called, "GRCh38_and_mm10-2020-A_build"

thanks.

**Comment by evolvedmicrobe** [comment]
@ahdee it appears you don't have any mouse cells in that sample.  The human UMI counts per barcode is typically >1K, while you don't observe any barcodes with mouse counts >60, and I suspect those are mapping artifacts and not real mouse DNA.  Are you sure you have mouse cells in this sample?

**Comment by ahdee** [comment]
@evolvedmicrobe thanks. However, I'm still a bit confused. Please see the attached image. I took another sample and aligned it just a simple GRCh38; I also align it with GRCh38_mm10; so first question is. 
1. why does the estimated cell go from 7K to 36K
2. on the scatter plot, what is happening here since most of the dots are multiplet? 
on the summary it mm10 Reads Mapped to Genome is only about .5%; should I just forget doing this and just go with the simple single GRCh38 alignment? 
Here is the image.  
![tRyL2vK 1](https://user-images.githubusercontent.com/9808122/137553915-a75d6dd2-5640-435b-a607-9e265abf8400.png)

**Comment by sitems** [comment]
I have flex gem-x experiment with PDX samples. I used 10x mixed/combined human+mouse reference. Should I also merge probe-set csv files for human and mouse?
