### ISSUE TITLE
Different ways to identify gtf format between version 7.0.0 and 7.2.0 of Cellranger 

### ISSUE THREAD

**Issue by lexuziandyu** [10XGenomics/cellranger#240]
Hi, recently when I was using the cellranger count command, I encountered an intresting problem. I used the mkref  command (version 7.2.0) to build a 10x genome of macaca mulatta [,](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_003339765.1/) using "GCF_003339765.1_Mmul_10_genomic.fna" and "genomic.gtf" files. It was just fine to run the following steps using version 7.0.0, but when I changed to 7.2.0, I got the error info below, using the same pre-built genome: 
`Parsing GTF on line 840: source: cannot contain spaces`
The line is like: 
`Line = 'NC_041754.1	Curated Genomic	gene	1747947	1748243	.	+	.	gene_id "MACMULV1R-PS1002"; db_xref "GeneID:100312438"; description "vomeronasal 1 receptor macMulV1R-ps1002 pseudogene"; gbkey "Gene"; gene "MACMULV1R-PS1002"; gene_biotype "pseudogene"; pseudo "true";'`
Here's my command:
`cellranger count --id=x \
 --transcriptome=~/ref/macaca_mulatta_NCBI \
 --fastqs=~/fastqs \
 --sample=sample1 \
 --localcores=16  \
 --include-introns=false \
 --nosecondary \
 --disable-ui`
I would really appreciate if you could help me to solve thsi problem. Thx!

**Comment by lilyle84** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
