### ISSUE TITLE
UMI indel correction

### ISSUE THREAD

**Issue by dakyung99** [10XGenomics/cellranger#241]
Hi Team !

How do you correct UMI indel error?

Kind regards,
DK

**Comment by dakyung99** [comment]
Also, 
Could you please share which tool do you use to correct umi errors? 

Thank you!

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.
