### ISSUE TITLE
Adjust the default setting to speed up read alignment

### ISSUE THREAD

**Issue by y9c** [10XGenomics/cellranger#25]
The `_BASIC_SC_RNA_COUNTER.ALIGN_READS` (STAR alignment) step in `cellranger count` pipeline is ultra slow.  The default setting of cellranger split the file int 96 chunks and alignment run one by one in a sequential  order. Meanwhile each STAR alignment run use only 4 CPU core. Seems this is the bottleneck of the whole pipeline. 

Some of other tools in cellranger can detect the core number in host machine and utilize the CPU usage.  

Increase the `threads` number in `cellranger-cs/3.0.2/mro/sc_rna_counter_cs.mro`  will doube the performance, but there is still other constraints in the settings.

**Comment by namisaghaei** [comment]
@yech1990 what are some of the constraints you are talking about? I'm also trying to cut down processing time by using as many cores/threads as possible in the parallelizable stages. I think generating fastqs and alignment are both completely parallelizable, but am struggling to optimize cellranger's use of cores on my machine.

**Comment by yech1990** [comment]
This line hard codes the thread. 
https://github.com/10XGenomics/cellranger/blob/5f5a6293bbc067e1965e50f0277286914b96c908/lib/python/cellranger/utils.py#L502
