### ISSUE TITLE
The same sample analysis use cellranger version 2.0.2 and version 3.0.2 quite differents

### ISSUE THREAD

**Issue by SeadonXing** [10XGenomics/cellranger#28]
Hi all : 
    I want to compare between cellranger 2.0 and 3.0 but I think the results are quite different .
    First :  I know that version 3.0 use new cell calling method.  I got 6688 cells by using version 3.0 while I only got 812 cells by using version 2.0 . My expect cells is about 4000 cells.  I think v 2.0 call cells are too little while v 3.0 are too many cells ? How to handle and choose ?
    Then : The sum UMIs in each cells is different also.  I cant find the mapping step change info of v 3.0 in release notes.  What changed for mapping and counts reads changed in v 3.0 compare to 2.0 ?  If I use v 2.0 for some samples and v 3.0 for other samples, can I still aggr them together to analysis ?

Best 
Seadon

**Comment by evolvedmicrobe** [comment]
Hi @SeadonXing,

* **Cell Calling** The Seurat package (e.g. https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html) contains methods that may help you further any questions with Cell Calling.

* **Alignment Step** A chimera filtering step was changed between v2.0 and v3.0, you may also be using a different genome, support@10xgenomics.com can provide further follow up.

* **Aggregation** Yes, v2.0 and v3.0 can be combined with `aggr` for analysis.

Warm wishes,
Nigel
