### ISSUE TITLE
Allow user to specify temp directory

### ISSUE THREAD

**Issue by chrisamiller** [10XGenomics/cellranger#29]
Right now, we're seeing that `cellranger count` jobs (on 5' scRNAseq data) can use up to a TB of disk during runtime. That drops down to a few dozen GB after completion - mostly the bam file.  

As we're using a cluster with lots of temp space on blades, it would be great to be able to specify a TEMPDIR as an option, so that those temp files can be written to local disk, without impacting more limited networked disk.  (It would also probably provide a significant speedup on many cluster architectures). 

I know cellranger is quite sensitive to directory structure during runtime, but could this even be as simple as just dropping a softlink into place?  We're also open to alternative ideas if you have any.  Thanks!

**Comment by bounlu** [comment]
I experienced the same issue, and solved it by modifying the python script `cellranger-cs/3.1.0/lib/python/cellranger/reference.py` adding these two lines:

find function `"index_reference"` and add this at the end of the args:
`args += ['--outTmpDir', '/your/desired/temp/directory']`

find function `"align"` next after above one and add this at the end of the args list:
`'--outTmpDir', '/your/desired/temp/directory',`
