### ISSUE TITLE
TypeError: len() of unsized object

### ISSUE THREAD

**Issue by konsolerr** [10XGenomics/cellranger#3]
I was running cell ranger pipeline trying to align reads from single-cell data to viral genome
the viral genome is pretty small, so instead of making mixture genome of mm10 and viral sequence I decided to align separately to mm10 and viral genome

I created an index genome from FASTA file and made GTF by my own, 
this GTF file contained only **one exon** and one CDS region.

After that, I got an error executing line 356 from file /lib/python/cellranger/transcriptome.py
`    chrom_bins = [bisect.bisect_left(tx_starts, cs) for cs in chrom_starts]`

TypeError: len() of unsized object from line

For me, it looks like when you read tables "transcriptInfo.tab"  and "exonInfo.tab" before   

```
    tx_info = np.loadtxt(tx_path, tx_dtype, skiprows=1, unpack=True)
    ex_info = np.loadtxt(ex_path, ex_dtype, skiprows=1, unpack=True)
```

if every file had only one line, then np.loadtxt will read a 1d array instead of 2d
to prevent this you can force np.loadtxt to read 2d array like

```
    tx_info = np.loadtxt(tx_path, tx_dtype, skiprows=1, unpack=True, ndmin=2)
    ex_info = np.loadtxt(ex_path, ex_dtype, skiprows=1, unpack=True, ndmin=2)
```

fix shown above seems to solve the problem

**Comment by pryvkin10x** [comment]
This should be fixed in 2.1 - the transcript annotation code is no longer in python.
