### ISSUE TITLE
cellranger mkgtf error 

### ISSUE THREAD

**Issue by JoaoGabrielMoraes** [10XGenomics/cellranger#32]
Hello,
 
I have single cell sequencing data from bovine endometrium and I am following 10x genomics instructions (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/references) to build a reference to use cellranger on bovine cells.
 
To do so, I’ve downloaded the GCF_002263795.1_ASR-UCD1.2_genomic.gff file from NCBI and converted it into a .gtf file using gffread.
 
Now, I tried to use cellranger mkgtf to filter the gtf file and got error below. Can somebody help with that?

[jmoraes@lewis4-r630-hpc4-node302 reference_genome]$ cellranger mkgtf /home/jmoraes/data/Illumina_example/Lucy_Moraes/outs/fastq_path/HY7FHBGX9/reference_genome/ASR_Converted.gtf output_GTF_TESTING.gtf --attribute=key:allowable_value
/storage/hpc/data/jmoraes/cellranger/cellranger-3.0.2/cellranger-cs/3.0.2/bin
cellranger mkgtf (3.0.2)
Copyright (c) 2019 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------
 
Writing new genes GTF file (may take 10 minutes for a 1GB input GTF file)...
Property 'gene_id' not found in GTF line 1791443: NC_006853.1   RefSeq  exon    364     430     .       +       .        transcript_id "rna78868";
 
Please fix your GTF and start again.

Thank you!!

**Comment by JoaoGabrielMoraes** [comment]
The problem was solved by using Emsembl genome (fasta) and annotation (gtf) files.

**Comment by hejian41** [comment]
It seems that column 9 of the gtf (transferred from gff3) must be 'gene_id "xxx"' and the order of column must be the same with gtf from Ensembl format. Try 'awk' command~
