### ISSUE TITLE
Error installing and running cellranger

### ISSUE THREAD

**Issue by quanphan08** [10XGenomics/cellranger#34]
Dear all,

I have recently installed cellranger on my Mac to create a .gtf file for Velocyto analysis.
I have installed cellranger -3.0.2 following the instruction on 10x website.
However I couldn't use any function from cellranger. Below is the screenshot of my error.
Any help would be appreciated.
(https://user-images.githubusercontent.com/35354607/57561036-6d464880-733e-11e9-84c7-2ce0e0891bd7.png)

**Comment by rleonriv** [comment]
I am having the same issue as you. Were you able to figure out how to fix it? Thanks!!

**Comment by quanphan08** [comment]
I have decided to run cellranger on a cluster - and it's working perfectly.
It might have to do with my PC hardwares maybe?

**Comment by pbpayal** [comment]
Same problem..trying to install on mac. Is there a solution to this? Can I download an older version?

**Comment by pbpayal** [comment]
I was able to install on 64GB RAM server. The previous one was 32GB, so it wasn't running.

**Comment by kesinger** [comment]
It appears that the error's in readlink, the version on osx has different arguments than the version on linux.  

If you have python in your path, one (untested) solution might be to replace line 29 with:

    export TENX_SCRIPTDIR=$(dirname `python -c "import os, sys; print(os.path.realpath(sys.argv[1]));" $0`)

**Comment by evolvedmicrobe** [comment]
Please reach out to support@10xgenomics.com for any issues you encounter for a fast response.  The code referenced in this issue has been completely rewritten and does not exhibit the current behavior, so am closing this issue.
