### ISSUE TITLE
cellranger count error exit status 2

### ISSUE THREAD

**Issue by lucyele** [10XGenomics/cellranger#35]
I run cellranger count and got this error:
[error] Pipestance failed. Error log at:
Aid/SC_RNA_COUNTER_CS/SC_RNA_COUNTER/_BASIC_SC_RNA_COUNTER/EXTRACT_READS/fork0/chnk087-ud4680f64f3/_errors

Log message:
exit status 2

How to solve it?  All files' MD5 are checked ok.

**Comment by mragsac** [comment]
I also have the same issue, but at the SORT_BY_POS step of Cell Ranger instead. Please let me know if you're able to figure things out.

**Comment by evolvedmicrobe** [comment]
Hi,
cellranger will usually run to compeletion, but it's hard to diagnose your issue without more information. Please contact support@10xgenomics.com for the best and most timely responses to issues like this.

Warm wishes,
Nigel
