### ISSUE TITLE
How to download older version of cellranger-3.0.2? Why isn't it in the Software Downloads page?

### ISSUE THREAD

**Issue by Sophia409** [10XGenomics/cellranger#38]
Hello, does anyone know how to download older version of cellranger-3.0.2? Why isn't it in the [Software Downloads](https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest) page?Because I have differents batches of data to deal with,and they belong to one experiment, I think change cellranger version among batches is bad. 
Unluckily, our linux server went wrong and I lost cellranger-3.0.2 package. Before I can download it in the Software Downloads page(as the old screenshot shows), but now it's replaced by latest version.I can find 3.0.0,but not 3.0.2.
Can anyone tell me the right page or share me with this package?By the way, does different versions of CellRanger 3.0 affect analysis result?

![图片](https://user-images.githubusercontent.com/30619010/62297827-7873c500-b4a4-11e9-953a-30082be96620.png)
@nlhepler

**Comment by nlhepler** [comment]
@Sophia409 Hello! I think you're looking for a little red button on the bottom right of the download page, which will have 3.0 as one of the options, which links to the 3.0.2 version you're looking for.

**Comment by Sophia409** [comment]
Thanks a lot!


On 8/2/2019 00:24，Lance Hepler<notifications@github.com> wrote：

@Sophia409 Hello! I think you're looking for a little red button on the bottom right of the download page, which will have 3.0 as one of the options, which links to the 3.0.2 version you're looking for.
