### ISSUE TITLE
Out of sync with CR tarball

### ISSUE THREAD

**Issue by mckinsel** [10XGenomics/cellranger#4]
The current version of Cell Ranger available from the [10x website](https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest) is 2.1.0. But, I believe this repo is 2.0.2. Do you plan to update this repo with the latest version of Cell Ranger?

**Comment by mckinsel** [comment]
Hey thanks Paul. Looking forward to it.

**Comment by pryvkin10x** [comment]
We finally got it through - apologies for the delay. The update process should be much smoother going forward.

**Comment by mckinsel** [comment]
Thanks very much Paul.
