### ISSUE TITLE
Considering release python modules to pypi or as separate repos?

### ISSUE THREAD

**Issue by nh3** [10XGenomics/cellranger#47]
Hello,

Given the MIT license, is there any chance that you might release python modules within CellRanger such as tenkit, cellranger, striped_smith_waterman, etc as individual packages to pypi or as separate repos? If not, would you permit other people doing so? I think this can be very useful to those wanting to use/develop based on those code but reluctant to clone/update the big repo. Many thanks!

**Comment by evolvedmicrobe** [comment]
Hi @nh3,

People are absolutely free to extend and build on the code within the restrictions of the license!  Some groups appear to already be undertaking such efforts (e.g. https://anaconda.org/hcc/cellranger).

Warm wishes,
Nigel
