### ISSUE TITLE
cellranger count-error fetching fastq file

### ISSUE THREAD

**Issue by Chenmengpin** [10XGenomics/cellranger#49]
Hi everyone,

I'm trying to run 'cellranger count' pipline to get the counts output data using the following code:

cellranger count --id=pbmc \
--fastqs=/mnt/c/Users/dell/scRNA/run_cellranger_count/pbmc_1k_v3_fastqs \
--sample=pbmc \
--transcriptome=/mnt/c/Users/dell/scRNA/run_cellranger_count/refdata-cellranger-GRCh38-3.0.0

But sadly got this error: "Error fetching io for 1923: no such file or directoryChecking sample info..."

It seems like unable to find the fastq files in the given directory, but it certainly does have the files, as the ls commend return the files name and it dose have all the fastq files needed:

DESKTOP-1T8GAGA:/mnt/c/Users/dell/scRNA/run_cellranger_count$ ls
pbmc  pbmc_1k_v3  pbmc_1k_v3_fastqs  refdata-cellranger-GRCh38-3.0.0

So I'm wondering what's wrong with the scripts or any tiny details that I missed.
Thank you !

**Comment by mvizosopatino** [comment]
I am running into similar issues, I would appreciate any feedback. Thank you
