### ISSUE TITLE
Where is Cellranger for Python 3?

### ISSUE THREAD

**Issue by mostafachatillon** [10XGenomics/cellranger#52]
Hi, I have python 3.7 in Anaconda and I can't install CellRanger. 
This repo is for Python 2.7, which is deprecated.

Where is CellRanger for Python 3?

**Comment by evolvedmicrobe** [comment]
Hi @mostafachatillon, Cell Ranger is a program composed of a variety of components and languages (Python, Go, Rust, Bash, Javascript) as well as associated third-party libraries.  At present, at present it is not distributed as part of the anaconda ecosystem, but is available from: https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest

**Comment by mostafachatillon** [comment]
Cell Ranger is distributed in anaconda here:

https://anaconda.org/hcc/cellranger

**Comment by evolvedmicrobe** [comment]
Oh cool! That looks like it's distributed by the University of Nebraska, and uses the old `3.0.2` version. 

https://github.com/unlhcc/hcc-conda-recipes/blob/master/recipes/cellranger/3.0.2/build.sh

I'd contact that Git repo for further assistance with the conda package.  At present 10X only supports a direct download or a clone of this code repository.

Also feel free to contact support@10xgenomics.com for further help.
