### ISSUE TITLE
How to Pip Install CellRanger ?

### ISSUE THREAD

**Issue by mostafachatillon** [10XGenomics/cellranger#53]
I am using Google Colab, and I want to install CellRanger, which can only be done with Pip or apt-get. How to do that?

**Comment by evolvedmicrobe** [comment]
The whole of Cell Ranger and it's dependencies is not available on PyPi, you may however be able to use a limited set of functionality by appending `../lib/python/` to the `PYTHONPATH`

**Comment by TheAustinator** [comment]
Would it be possible to add a `setup.py` in `../lib/python/cellranger` so that it could be manually installed?
