### ISSUE TITLE
Suggestion: using refgenie for reference indexes

### ISSUE THREAD

**Issue by nsheff** [10XGenomics/cellranger#55]
Hi -- the `mkref` function of cell ranger is producing a strictly structured folder hierarchy that includes  some indexes and resources needed by the software. While the folder structure makes it easy for cellranger to locate the things it needs, it also makes these resources less portable for other tools. We recently developed a tool called [refgenie](http://refgenie.databio.org/) that solves this problem in a way that is more universal, so that the resources can be re-used by many different tools. The resources required by cellranger are actually pretty generic and are useful outside of the cellranger context. I wondered if you had any interest in adapting the cellranger system so that it could use refgenie assets. This would give advantages both to cellranger developers and also to users: for example, users would only need refgenie-based STAR indexes or GTF files instead of having to have these in separate places for different tools; and cellranger development would become simplified because it could outsource tracking down reference files to refgenie, instead of having to manage it internally.

Let me know what you think.

**Comment by nsheff** [comment]
@sreenathkrishnan do you know who I should contact about this question? Thanks!

**Comment by nsheff** [comment]
I"m guessing that's a "not interested" ?

**Comment by elehnert10x** [comment]
GitHub issues are not currently monitored by our support team, so we are closing out older issues and attempting to move active issues to more responsive channels. I will open a ticket with your suggestion for review by our team.
