### ISSUE TITLE
problem in install cellranger

### ISSUE THREAD

**Issue by yueli711** [10XGenomics/cellranger#58]
Hello,

I am trying to install cellranger-3.1.0 in my server.

Thanks in advance for great help!

Best,

Yue

    Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-23-generic x86_64)

    ~/opt01/cellranger-3.1.0$ export PATH="/home/yli1/opt01/cellranger-3.1.0:$PATH"
    ~/opt01/cellranger-3.1.0$ cellranger
    /home/yli1/opt01/cellranger-3.1.0
    /home/yli1/opt01/cellranger-3.1.0/cellranger: line 31: /home/yli1/opt01/cellranger-3.1.0/../tenkit/bin/common/_master: No such file or directory

**Comment by evolvedmicrobe** [comment]
Hi, please send an email to support@10xgenomics.com who will be able to assist you further.
