### ISSUE TITLE
Issue with bcl2fastq

### ISSUE THREAD

**Issue by sbhattacharya3** [10XGenomics/cellranger#6]
Hi,

I have installed bcl2fastq and cell ranger, for using the mkfastq command. It was working fine, but it has just stopped working. To verify whether I messed up with the PATH, I installed cell ranger and bcl2fastq on a different system, and run the commands from there. I am still getting errors.
Please find below the commands
##Checking the version of bcl2fastq
[sbhattach2@CRI-13-130 cellranger-2.1.0]$ **bcl2fastq --version** 
BCL to FASTQ file converter
bcl2fastq v2.20.0.422
Copyright (c) 2007-2017 Illumina, Inc.
##running mkfastq
[sbhattach2@CRI-13-130 cellranger-2.1.0]$ sudo ./cellranger mkfastq --id=single_cell_zhe --run=/data/Suro/180112_NS500434_0271_AHFCW5BGX5/ --samplesheet=/home/sbhattach2/Sample_Zhe.csv
/home/sbhattach2/cellranger-2.1.0/cellranger-cs/2.1.0/bin
cellranger mkfastq (2.1.0)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

Martian Runtime - '2.1.0-2.3.0'
Serving UI at http://CRI-13-130:34100?auth=HvO_950umeofy7Jo1aYtXyKrK3lEiBUDzbXi_pjVOZ0

Running preflight checks (please wait)...
Checking run folder...
Checking RunInfo.xml...
Checking system environment...
Checking barcode whitelist...
Checking read specification...
Checking samplesheet specs...

**[error] No bcl2fastq found on path. demux requires bcl2fastq v2.17 or greater for RTA version: 2.4.11**

Can you please guide me regarding the changes I need to make?

Thanks in advance,
Surajit

**Comment by pryvkin10x** [comment]
Hello,

I assume you were able to get help through our official support email since this question relates to an official release.
