### ISSUE TITLE
How can I convert a barcoded bam to read count matrix?

### ISSUE THREAD

**Issue by biobug16** [10XGenomics/cellranger#61]
Hi @evolvedmicrobe and all,
I am new with scRNA Seq analysis and just having a barcoded bam. I am not sure how should I convert this barcoded bam to a count matrix. 
I may be missing something. Any help to wards this will be highly appreciated.
Thanks

**Comment by evolvedmicrobe** [comment]
If you don't have the original FASTQ files you'll have to back convert to FASTQ to run Cell Ranger, I'd contact support@10xgenomics.com for more help.
