### ISSUE TITLE
Making a new reference for miRNA in 10X genomics data

### ISSUE THREAD

**Issue by biobug16** [10XGenomics/cellranger#62]
Hi @evolvedmicrobe and All,
I want to build a new ref genome using cellranger to capture miRNA profile in scRNA data from 10X genomics. For which I started with UCSC gtf file and performed `grep` for "MIR" to get a filtered gtf file. This filtered gtf file was then used with `mkref` to build reference genome only for the miRNAs. But I am unable to use this genome further with `cellranger count`.
Is that a correct approach? Correct me please if I am missing something.

Thanks

**Comment by LehmannN** [comment]
What's the error you get when you run `cellranger count` ? You approach seems correct, just be careful if you took your GTF from the UCSC table browser, there are some known issues (check https://genome.ucsc.edu/FAQ/FAQdownloads.html#download37). If you got you're data from there, I would recommend you to download the GTF file from here: https://hgdownload.soe.ucsc.edu/downloads.html

**Comment by biobug16** [comment]
Hi @LehmannN ,
After downloding the GTF file again as you suggested, its working perfectly fine now.
Thanks for your help.

**Comment by LehmannN** [comment]
I'm glad this helped !

**Comment by biobug16** [comment]
Hi All and @LehmannN ,
I have a followup question, after mapping with filtered gtf using cellranger count with default settings, I found only 0% of mapping and 1 Median Genes per Cell. 
Do I need to change some parameters while mapping or I am doing anything incorrect.
Any suggestions will be highly appreciated.
Thanks
