### ISSUE TITLE
Process possorted bam directly to count matrix

### ISSUE THREAD

**Issue by jasperpanten** [10XGenomics/cellranger#64]
Many of the SRA submissions seem to contain the bam output for 10x scRNA-Seq data - it seems a bit silly to convert that back to fastq to then re-align it via cellranger. 
Is there functionality in CellRanger to directly process the bam files or could someone comment on which steps CellRanger takes after the bam file is generated? It would be easy enough to just use pysam to count the UMIs per annotated gene/cell, but I'm guessing the pipeline involves more filtering steps. Thanks in advance and apologies if this has already been asked.

**Comment by evolvedmicrobe** [comment]
Hi @jasperpanten,

There is no functionality in Cell Ranger to rerun from a BAM, although it might seem a bit silly to convert back, we felt that [providing a tool](https://support.10xgenomics.com/docs/bamtofastq) to do the conversion and then allowing a simple run from the outputs would be the easiest path for the end user experience, and allows us to keep our documentation and validation simple.  Please feel free to reach out to support@10xgenomics.com if you'd like to follow up more though.

Warm wishes,
N
