### ISSUE TITLE
release 3.1.0

### ISSUE THREAD

**Issue by idot** [10XGenomics/cellranger#65]
Hello, 
would it be possible to release a new version of the pipeline in the same way that is available at 
https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest ?
I put it into a container and the problem is that the link expires, so I always have to copy paste again whenever I build the container.
This also applies to the ATAC pipeline.

Thank you very much,
ido

**Comment by evolvedmicrobe** [comment]
Hi @idot could you describe the use case a little more? Are you making a docker container you then redistribute?  Are you not able to just point to a location where you've previously downloaded the tarball?

**Comment by idot** [comment]
Dear Nigel,
I wanted to make an internal docker container. The download link that is generated expires - so my build is not reproducible after a few days and I have to go again to the page, fill out the form, get the new download link etc ... its not really a big deal, but a nice to have. I'm closing this now.

thank you very much,
ido


example download link that I changed, so that people can not simply copy it:
```
curl -o cellranger-3.1.0.tar.gz "http://cf.10xgenomics.com/releases/cell-exp/cellranger-3.1.0.tar.gz?Expires=1588300266&Policy=eyJTdGLmNvbS9yZWxlYXNlcy9jZWxsLWV4cC9jZWxscmFuZ2VyLTMuMS4wLnRhci5neiIsIkNvbmRpdGlvODMwMDI2Nn19fV19&Signature=RYUYWT5cJdjFwDu1p1n9JSrd-9M~~TjNMw-NLiPcCBvJUlSc8wG6a0dSW-BtNHgJj2nAv-Wfla7TRu6WrYgMAjWg-exh76dFufOvLN1taFRuWDdvdaJ9GRHJtyaVe1qvEPPJv02k2nrMs1-Nz9vqiw9Ibzfz~oA5NRx4Q__&Key-Pair-Id=APKPDA"
```
