### ISSUE TITLE
 Unable to convert single cell RNA Seq bam to fastq using cellranger's bamtofastq

### ISSUE THREAD

**Issue by biobug16** [10XGenomics/cellranger#66]
Hi @evolvedmicrobe I have a quick question, i have few aligned bam files from single cell RNA Seq data. I want to regenerate fastqs from them. In order to do so i am using cellranger's bamtofastq and I am also getting fastq files but in the specified path within a folder named “MissingLibrary_1_flowcellName”. I am not sure what does this mean? Why the generated folder is named as missing library. Does anybody have any idea about this?

The command I used is:
`cellranger bamtofastq possorted_genome_bam.bam ./sample
`
Any help to resolve this will be highly appreciated.

Thanks

**Comment by alexcwsmith** [comment]
bamtofastq is a standalone executable file made by 10X, not part of the cellranger pipeline, so you do not need the 'cellranger' prefix. an example of the correct command, is to be in the terminal inside the directory with the bamtofastq executable, and then run:

`./bamtofastq-1.2.0 --nthreads=24 1017/1017_possorted_genome_bam.bam 1017_fastqs`

take note this requires you to run:

`chmod 700 bamfastq-1.2.0`

to make it executable first
