### ISSUE TITLE
'Found 0 or >1 features for confidently mapped read/pair

### ISSUE THREAD

**Issue by shaaaarpy** [10XGenomics/cellranger#67]
Hi 
i got this issue for my public data. 
![image](https://user-images.githubusercontent.com/23281566/76982825-73e01c00-6962-11ea-92eb-ce1c36040637.png)
can you please tell  what the issue is?

**Comment by evolvedmicrobe** [comment]
Hi @shaaaarpy, That error was produced at this line of code: https://github.com/10XGenomics/cellranger/blob/5f5a6293bbc067e1965e50f0277286914b96c908/lib/rust/cr_stage/src/cmd_mark_dups.rs#L291 I'd reach out to support@10xgenomics.com for further follow up, it can indicate the input files are corrupted or some other problem they'll be well equipped to address.
