### ISSUE TITLE
Anyone used for unmodified HTO primers vs. modified HTO primers?

### ISSUE THREAD

**Issue by Jimmyyun** [10XGenomics/cellranger#69]
Hi 
I was following the old cell hashing protocol, which was without phosphorothioate modification in HTO cDNA PCR additive primer, SI-PCR primer, and TruSeq D701_s primer. However, it seems now all three primers use the phosphorothioate modification. I understand the purpose of using that modification that is for inhibiting nuclease degradation. 
Has anyone seen the difference in the Cell Hashing case? Does it make a difference enough to get much better quality data? 
Best

**Comment by evolvedmicrobe** [comment]
Hi @Jimmyyun,

10X has announced at AGBT we'll release a cell multiplexing protocol, but at present we do not have a supported solution.  I'd encourage you to reach out to the relevant method developers for more help with this issue.

Warm wishes,
N
