### ISSUE TITLE
Use a different colormap/palette in gene expression visualizations

### ISSUE THREAD

**Issue by wflynny** [10XGenomics/cellranger#7]
https://github.com/10XGenomics/cellranger/blob/aba5d379169ff0d4bee60e3d100df35752b90383/lib/python/cellranger/webshim/constants/gex.py#L561

It would be better if instead of `Jet`, which is [a problematic colormap](https://matplotlib.org/users/colormaps.html#miscellaneous), a perceptually uniform colormap was used.  Included in Plotly is [Viridis](https://github.com/plotly/plotly.js/blob/eeef0ed4bfca0297dcfee09f2e864668d60dcbe6/src/components/colorscale/scales.js#L118) but really [any sequential colormap](https://plot.ly/ipython-notebooks/color-scales/) is better than `Jet`.   By choosing a better default, you can hopefully help people move away from using `Jet`.

**Comment by evolvedmicrobe** [comment]
We've enabled alternate color schemes in the new Visium product offering, including Viridis (see the analysis tab here: http://cf.10xgenomics.com/samples/spatial-exp/1.0.0/V1_Breast_Cancer_Block_A_Section_1/V1_Breast_Cancer_Block_A_Section_1_web_summary.html).  Survey's indicated Jet was still preferred, but we may visit that later.
