### ISSUE TITLE
the v_gene is None in all of  samples with the command of cellranger vdj 

### ISSUE THREAD

**Issue by WellJoea** [10XGenomics/cellranger#70]
IN=PATH/RawData
ID=$1
VDJ38=PATH/refdata-cellranger-vdj-GRCh38-alts-ensembl-3.1.0
CR=PATH/cellranger-3.1.0/cellranger
$CR vdj --id=${ID}_vdj \
    --fastqs=$IN/${ID}-1,$IN/${ID}-2,$IN/${ID}-3,$IN/${ID}-4 \
    --sample=${ID}-1,${ID}-2,${ID}-3,${ID}-4 \
    --reference=$VDJ38

I use the command to annotate the vdj fastq, but all of the samples  is None in v_gene column

**Comment by WellJoea** [comment]
The v gene is none because the illumina PE seq cannot read though all of the cdr3 region?

**Comment by wyattmcdonnell** [comment]
Hi @WellJoea what kind of cells are you working with?
