### ISSUE TITLE
filtered_feature_bc_matrix  batch effect

### ISSUE THREAD

**Issue by WellJoea** [10XGenomics/cellranger#71]
Hi, 
Dear Prof.
   I want to know whether the the matrix of filtered_feature_bc_matrix  files  in aggr have been corrected by batch effect as I removed  batch effect in the command of "cellranger aggr" by setting "batch" in --csv file

Thanks!

**Comment by evolvedmicrobe** [comment]
The best source for batch effect documentation is the support pages here: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/aggregate, and please feel free to reach out to support@10xgenomics.com if you encounter other issues.

Warm wishes,
Nigel
