### ISSUE TITLE
[error] FASTQ files differ in number. Exiting pipeline.

### ISSUE THREAD

**Issue by yejg2017** [10XGenomics/cellranger#72]
When I run cellranger count with fastsqs:
DME-6_S1_L001_I1_001.fastq.gz
DME-6_S1_L001_R1_001.fastq.gz
DME-6_S1_L001_R2_001.fastq.gz
DME-6_S2_L001_R1_001.fastq.gz
DME-6_S2_L001_R2_001.fastq.gz
DME-6_S3_L001_I1_001.fastq.gz
DME-6_S3_L001_R1_001.fastq.gz
DME-6_S3_L001_R2_001.fastq.gz
DME-6_S4_L001_R1_001.fastq.gz
DME-6_S4_L001_R2_001.fastq.gz
 And I got this error,but the tutorial tell me that the I1 index file is optional,I do not how to fixed this issue,Counld you help me?Thanks

**Comment by evolvedmicrobe** [comment]
The fastq reqd file types need to be consistent, so either all files must have an `I1` or none of them should.  Feel free to reach out to support@10xgenomics.com for more information.

**Comment by yejg2017** [comment]
Thanks!And I want to ask for help for an another problem.When I run cellranger-atac count with fastqs:
CAT-08_S1_L001_I1_001.fastq.gz
CAT-08_S1_L001_R1_001.fastq.gz
CAT-08_S1_L001_R2_001.fastq.gz
CAT-08_S1_L001_R3_001.fastq.gz
CAT-08_S2_L001_I1_001.fastq.gz
CAT-08_S2_L001_R1_001.fastq.gz
CAT-08_S2_L001_R2_001.fastq.gz
CAT-08_S2_L001_R3_001.fastq.gz
CAT-08_S3_L001_I1_001.fastq.gz
CAT-08_S3_L001_R1_001.fastq.gz
CAT-08_S3_L001_R2_001.fastq.gz
CAT-08_S3_L001_R3_001.fastq.gz
CAT-08_S4_L001_I1_001.fastq.gz
CAT-08_S4_L001_R1_001.fastq.gz
CAT-08_S4_L001_R2_001.fastq.gz
CAT-08_S4_L001_R3_001.fastq.gz
 
The log file told me the error: [error] Input FASTQ file is not gzipped but filename has /home/ye/Data/Su/20190554/ATAC/U-N-5/U-N-5_S3_L002_R2_001.fastq.gz suffix: .gz

**Comment by celinesin** [comment]
I also have this problem, but I don't have any I1 files
However, I do have 11 lanes:

headb_S1_L001_R1_001.fastq.gz  headb_S1_L006_R2_001.fastq.gz
headb_S1_L001_R2_001.fastq.gz  headb_S1_L007_R1_001.fastq.gz
headb_S1_L002_R1_001.fastq.gz  headb_S1_L007_R2_001.fastq.gz
headb_S1_L002_R2_001.fastq.gz  headb_S1_L008_R1_001.fastq.gz
headb_S1_L003_R1_001.fastq.gz  headb_S1_L008_R2_001.fastq.gz
headb_S1_L003_R2_001.fastq.gz  headb_S1_L009_R1_001.fastq.gz
headb_S1_L004_R1_001.fastq.gz  headb_S1_L009_R2_001.fastq.gz
headb_S1_L004_R2_001.fastq.gz  headb_S1_L010_R2_001.fastq.gz
headb_S1_L005_R1_001.fastq.gz  headb_S1_L011_R1_001.fastq.gz
headb_S1_L005_R2_001.fastq.gz  headb_S1_L011_R2_001.fastq.gz
headb_S1_L006_R1_001.fastq.gz
