### ISSUE TITLE
Thanks!And I want to ask for help for an another problem.When I run cellranger-atac count with fastqs:

### ISSUE THREAD

**Issue by yejg2017** [10XGenomics/cellranger#73]
Thanks!And I want to ask for help for an another problem.When I run cellranger-atac count with fastqs:
CAT-08_S1_L001_I1_001.fastq.gz
CAT-08_S1_L001_R1_001.fastq.gz
CAT-08_S1_L001_R2_001.fastq.gz
CAT-08_S1_L001_R3_001.fastq.gz
CAT-08_S2_L001_I1_001.fastq.gz
CAT-08_S2_L001_R1_001.fastq.gz
CAT-08_S2_L001_R2_001.fastq.gz
CAT-08_S2_L001_R3_001.fastq.gz
CAT-08_S3_L001_I1_001.fastq.gz
CAT-08_S3_L001_R1_001.fastq.gz
CAT-08_S3_L001_R2_001.fastq.gz
CAT-08_S3_L001_R3_001.fastq.gz
CAT-08_S4_L001_I1_001.fastq.gz
CAT-08_S4_L001_R1_001.fastq.gz
CAT-08_S4_L001_R2_001.fastq.gz
CAT-08_S4_L001_R3_001.fastq.gz
 
The log file told me the error: [error] Input FASTQ file is not gzipped but filename has CAT-08_S1_L001_R2_001.fastq.gz  suffix: .gz

_Originally posted by @yejg2017 in https://github.com/10XGenomics/cellranger/issues/72#issuecomment-612715918_

**Comment by evolvedmicrobe** [comment]
Hi @yejg2017,

Please reach out to support@10xgenomics.com, you appear to be passing files with a gzipped suffix that are not gzipped per the code here:

https://github.com/10XGenomics/cellranger/blob/5f5a6293bbc067e1965e50f0277286914b96c908/mro/stages/common/setup_chunks/__init__.py#L199

Cheers,
N
