### ISSUE TITLE
Cell number looks different after using cellranger aggr

### ISSUE THREAD

**Issue by WayneForever** [10XGenomics/cellranger#74]
Hi,

I'm now working on one 10x project with using data from two samples. I firstly applied cellranger count on two samples seperately and now I need to combine these two results by using cellranger aggr. 

However, after I got the final result from cellranger aggr with the version of 3.1, I checked the result from the html report. What suprised me was that the 'Estimated Number of Cells' shown in the left with green letters ( 7947) was different with the number listed on the right, which was 15,894. I checked the matrix file converted from the final result and number of cells was checked to be 7947. The figure attched is just the screen shot of the result. 

Therefore, I'm wondering the reason why these two numbers are different. 

I'm very grateful if someone could help me out. Thanks a lot.

![image](https://user-images.githubusercontent.com/41728823/79324950-f13b8400-7f42-11ea-8284-fe0ed33c0b41.png)

**Comment by WayneForever** [comment]
I checked the number by using Seurat 'Read10X' function, and the result goes like this:

> pbmc <- CreateSeuratObject(pbmc.data, min.cells = 0, min.features = 0, project = "10X_PBMC", names.field = 2, names.delim = "-")
> pbmc
An object of class Seurat 
60617 features across 7947 samples within 1 assay 
Active assay: RNA (60617 features)

It seems like it coordinates with the number on the left.

**Comment by evolvedmicrobe** [comment]
Hi @WayneForever,

Feel free to reach out to support@10xgenomics.com for fast responses to issues like this.  This was a known bug in CR 3.1 where the summation was wrong, and as you pointed out the number on the left is the correct number to reference.  This has been patched in the current version of the code, and support might be able to send you a patch file if you email them.

Cheers,
Nigel
