### ISSUE TITLE
naming of jobmanager templates, `*.template` versus `*.template.example`

### ISSUE THREAD

**Issue by jbloom** [10XGenomics/cellranger#8]
When I try running `cellranger` version 2.1.0, I get the following error:
```
ls: cannot access /fh/fast/bloom_j/software/cellranger/martian-cs/2.3.0/jobmanagers/*.template: No such file or directory
```

The problem appears to be that the relevant files are named `*.template.example`, not `*.template`.

For instance, `ls martian-cs/2.3.0/jobmanagers/` yields:
```
config.json              retry.json            slurm.template.example
lsf.template.example     sge_queue.py          torque.template.example
pbspro.template.example  sge.template.example
```

**Comment by wflynny** [comment]
Not a developer, but where in the run do you encounter this problem?  

Looks like the only place that check arises is during sitecheck, and stderr should be piped to `/dev/null` during the check.  What do the last two entries in the `_sitecheck` file for that job look like?

**Comment by adam-azarchs** [comment]
What is the command line you are using to run?  Are you setting `--jobmode`?  If so, you need to have the corresponding template configured.

**Comment by jbloom** [comment]
Here are some examples. The problem exists with version 2.1.0, but not version 2.0.0:

This works:
```
jbloom@rhino3:/fh/fast/bloom_j/software$ cellranger mkfastq --version && cellranger sitecheck > sitecheck.txt
cellranger mkfastq (2.0.0)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------
```

But this does **not**:
```
jbloom@rhino3:/fh/fast/bloom_j/software$ ./cellranger-2.1.0/cellranger mkfastq --version && ./cellranger-2.1.0/cellranger sitecheck > sitecheck.txt
/fh/fast/bloom_j/software/cellranger-2.1.0/cellranger-cs/2.1.0/bin
cellranger mkfastq (2.1.0)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

ls: cannot access /fh/fast/bloom_j/software/cellranger-2.1.0/martian-cs/2.3.0/jobmanagers/*.template: No such file or directory
```

And this works:
```
cellranger mkfastq --version && cellranger testrun --id=tiny 
cellranger mkfastq (2.0.0)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

cellranger testrun (2.0.0)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

Running Cell Ranger in test mode...

Martian Runtime - 2.0.0 (2.1.3)
2018-02-15 05:54:16 [runtime] Reattaching in local mode.
2018-02-15 05:54:16 [runtime] Found orphaned stage: ID.tiny.SC_RNA_COUNTER_CS.SC_RNA_COUNTER.SETUP_CHUNKS
```
(not showing rest of output)

But this does **not** due to the same error as above:
jbloom@rhino3:/fh/fast/bloom_j/software$ ./cellranger-2.1.0/cellranger mkfastq --version && ./cellranger-2.1.0/cellranger testrun --id=tiny
/fh/fast/bloom_j/software/cellranger-2.1.0/cellranger-cs/2.1.0/bin
cellranger mkfastq (2.1.0)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

/fh/fast/bloom_j/software/cellranger-2.1.0/cellranger-cs/2.1.0/bin
cellranger testrun (2.1.0)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

Running Cell Ranger in test mode...

Martian Runtime - '2.1.0-2.3.0'
2018-02-15 05:54:53 [jobmngr] WARNING: configured to use 339GB of local memory, but only 224.7GB is currently available.

RuntimeError: pipestance 'tiny' already exists with different invocation file /fh/fast/bloom_j/software/tiny/_invocation

2018-02-15 05:54:54 Shutting down.
ls: cannot access /fh/fast/bloom_j/software/cellranger-2.1.0/martian-cs/2.3.0/jobmanagers/*.template: No such file or directory
Saving pipestance info to tiny/tiny.mri.tgz
For assistance, upload this file to 10x Genomics by running:

cellranger upload <your_email> tiny/tiny.mri.tgz
```

**Comment by adam-azarchs** [comment]
I can't reproduce this on a fresh install, and that error should be getting suppressed and ignored.  So something weird is going on here.  Was this actually stopping progress or just a warning message?

I'd theorize that there might be something unusual about your `.bashrc` which would alter the behavior.  If you could share the output of `shopt` and `alias` that might clarify things.

This information would be helpful to make a more permanent fix, but as a temporary workaround if this is blocking your work, you can comment out that part of the sitecheck (https://github.com/10XGenomics/cellranger/blob/master/tenkit/bin/sitecheck#L82).  If you have further problems you should contact support@10xgenomics.com.

**Comment by jbloom** [comment]
It's just a warning, not an error it turns out. So maybe not worth worrying about...
