### ISSUE TITLE
cellranger vdj defined less cells, than expected

### ISSUE THREAD

**Issue by soda-bottle** [10XGenomics/cellranger#80]
Hi!
I tried to analyze PBMCs of a Healthy Donor (v1) dataset from 10x website, using `cellranger vdj`. So I've downloaded VDJ Ig - FASTQs and ran the pipeline with this `(refdata-cellranger-vdj-GRCh38-alts-ensembl-3.1.0) `reference. Compared to summary for this dataset, provided on website, I've got ~10 times less cells and as a consequence 10 times more reads per cell. QC (Q30, number of reads and correct barcodes) is the same for my summary and the one on website. I was wondering, what could be the issue? 
Thanks in advance!

I ran the pipeline with the following command:
`cellranger vdj --id=cell_ranger_1_1 \ `
`--fastqs=/home/stasya/pbmc/vdj_v1_hs_pbmc3_b_26x91_fastqs/ \`
`--sample=vdj_v1_hs_pbmc3_b_26x91 \`
`--reference=/home/stasya/cell_ranger/refdata-cellranger-vdj-GRCm38-alts-ensembl-3.1.0`

**Comment by felixhell2004** [comment]
Do you use 'cellranger count ' this functions to call cells, which to identify the the real cells by barcode?
