### ISSUE TITLE
the difference between CellRanger Vesion 3.0.2 and 3.1.0

### ISSUE THREAD

**Issue by wangteng0605** [10XGenomics/cellranger#87]
Dear authors,
Is there any difference with the output results from different CellRanger Vesion between 3.0.2 and 3.1.0?
Thanks so much!

**Comment by evolvedmicrobe** [comment]
The release notes document the important changes: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/3.1/release-notes
