### ISSUE TITLE
cellranger count: bad argument handling

### ISSUE THREAD

**Issue by cschu** [10XGenomics/cellranger#9]
Would it be possible to issue warnings when unknown/mistyped command line parameters are used?  v2.1.1 just silently does nothing in such a case (typed --samples instead of --sample, wasted a lot of time, could be handled better by an argument handler checking the arguments)

**Comment by evolvedmicrobe** [comment]
Hi @cschu, yes this would be a good idea! The problem is caused by the library `docopt` we use for argument parsing, which may be removed in a future version.  Thank you for the feedback.
