### ISSUE TITLE
Cellranger count error version3.1.0 

### ISSUE THREAD

**Issue by martitroiani** [10XGenomics/cellranger#90]
Hi, 
I'm aligning 10x cell data with cellranger count but I'm having problems in the alignment step.
This is the error 

Log message:
Traceback
(most recent call last):
  File
"path/cellranger-3.1.0/martian-cs/v3.2.3/adapters/python/martian_shell.py",
line 589, in _main
  stage.main()
  File
"path/cellranger-3.1.0/martian-cs/v3.2.3/adapters/python/martian_shell.py",
line 554, in main
  self._run(lambda: self._module.main(args,
outs))
  File
"path/cellranger-3.1.0/martian-cs/v3.2.3/adapters/python/martian_shell.py",
line 523, in _run
  cmd()
  File "path/cellranger-3.1.0/martian-cs/v3.2.3/adapters/python/martian_shell.py",
line 554, in <lambda>
  self._run(lambda: self._module.main(args,
outs))
  File
"path/cellranger-3.1.0/cellranger-cs/3.1.0/mro/stages/counter/align_reads/__init__.py",
line 128, in main
  align_reads(args, outs)
  File
"path/cellranger-3.1.0/cellranger-cs/3.1.0/mro/stages/counter/align_reads/__init__.py",
line 67, in align_reads
  read_group_tags=tk_bam.make_star_rg_header(args.read_group))
  File
"path/cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/reference.py",
line 616, in align
  raise cr_io.CRCalledProcessError(e.msg + '
Check STAR logs for errors: %s .' % star_log)
CRCalledProcessError:
Process returned error code -7: STAR . Check STAR logs for errors:

Can someone help me because I don't know how to solve the problem.
Thank you in advance 
Best

**Comment by evolvedmicrobe** [comment]
Hi, I'd recommend using the latest version of cellranger.  Please contact support@10xgenomics.com for further help with this issue.
