### ISSUE TITLE
Unable to distinguish between [SC5P-R2, SC3Pv2] chemistries based on the R2 read mapping for Sample

### ISSUE THREAD

**Issue by CadenZhao** [10XGenomics/cellranger#92]
Fastqs downloaded from SRA:
![image](https://user-images.githubusercontent.com/30337666/92454913-9e18e500-f1f3-11ea-9f81-ddcba11fe582.png)

My shell scripts to iteratively run cellranger count:
```
#!/usr/bin/bash

ref_dir=../../input/ref/refdata-gex-mm10-2020-A
fq_dir=../../input/SRA/fastq

for i in `ls ${fq_dir}`
do
    sample="${fq_dir}/${i}"
    cellranger count --id=${i} --fastqs=${sample} --transcriptome=${ref_dir} --localcores=32
done
```

ERROR I got:
![image](https://user-images.githubusercontent.com/30337666/92454278-eaaff080-f1f2-11ea-924e-0a307b3791e1.png)

Among 14 samples, 7 can be processed successfully:
![image](https://user-images.githubusercontent.com/30337666/92456297-4f6c4a80-f1f5-11ea-872b-e5690fede598.png)

One ERROR is different from others:
![image](https://user-images.githubusercontent.com/30337666/92456654-cb669280-f1f5-11ea-8e31-8a8caa075ad2.png)
I fount this file size is different from the file in SRA, I'll re-download it.

But file sizes in the other 6 ERRORs are same as files in SRA. How should I debug it?

Thank you very much!

**Comment by CadenZhao** [comment]
BTW, software version:
_cellranger 4.0.0_

**Comment by dadkhahk** [comment]
@CadenZhao I wondered if you got any response from 10x to this issue as I got the same error message for several samples recently. Thanks!
Kimia

**Comment by evolvedmicrobe** [comment]
Please contact support@10xgenomics.com for help with this issue.

**Comment by longrw** [comment]
@CadenZhao @evolvedmicrobe @dadkhahk i wonder if you got any response from 10X to this issue as i got the same error message. Thinks!
longrw

**Comment by dadkhahk** [comment]
Not here. 10x usually doesn't respond here and they are more responsive through email. They will ask for some files to be provided so they can figure out the issue: support@10xgenomics.com

**Comment by longrw** [comment]
> In order to distinguish between the 3' vs 5' assay configuration the following conditions need to be satisfied:
- A minimum of 1000 confidently mapped reads
- A minimum of 5.0% of the total reads considered needs to be confidently mapped
- The number of sense reads need to be at least 2x compared to the antisense reads or vice versa
Please validate the inputs and/or specify the chemistry via the --chemistry argument.

![chemistry](https://user-images.githubusercontent.com/15103000/125723344-c9c3cf89-a84c-4dd6-8e52-925316978d1f.jpg)

**Comment by longrw** [comment]
> In order to distinguish between the 3' vs 5' assay configuration the following conditions need to be satisfied:
> - A minimum of 1000 confidently mapped reads
> - A minimum of 5.0% of the total reads considered needs to be confidently mapped
> - The number of sense reads need to be at least 2x compared to the antisense reads or vice versa
> 
> Please validate the inputs and/or specify the chemistry via the --chemistry argument.

![chemistry](https://user-images.githubusercontent.com/15103000/125723468-25aa6d5c-4a23-4f3d-bd05-776a43f9b205.jpg)
