### ISSUE TITLE
Error checking installation

### ISSUE THREAD

**Issue by marctormo** [10XGenomics/cellranger#93]
Hi,

I'm trying to check the installation but I get the following error:
$ cellranger testrun --id=tiny
 error opening .env.json file

I'm working in a cluster but I can't see where this file should be.
Do you have any idea?

Many thanks,
Marc

**Comment by marctormo** [comment]
I'm sorry, my fault. I deleted it somehow

**Comment by evolvedmicrobe** [comment]
Glad the issue was resolved, feel free to email support@10xgenomics.com for quick help with any other problems that occur.

**Comment by shenzhongjun** [comment]
> I'm sorry, my fault. I deleted it somehow

Hi，marctormo！May I know what file is this, and where should it be? I also encountered the same problem, and I couldn't find the location of this file.
