### ISSUE TITLE
R1 and R2 fastq

### ISSUE THREAD

**Issue by huwenhuo** [10XGenomics/cellranger#95]
I somehow got only R1 and R2 fastq files after submitted as Amplicon-Seq. How can I convert these two files of R1/R2 fastq to I1, R1, R2 three fastq files using cell ranger?

**Comment by Eddylyf** [comment]
I have similar issue, I downloaded data from EBI that only have two fastq.gz files (R1 and R2), I renamed them as suggested (A1_S1_L001_R1_001.fastq.gz, A1_S1_L001_R2_001.fastq.gz), but still can not run cellranger, could anybody help me? Many thanks!

**Comment by kelvinlee760948065** [comment]
I have an error showing that FASTQ header mismatch detected

**Comment by andreschamorro** [comment]
I have similar issue, maybe the following forum can be of help :
[https://forum.qiime2.org/t/how-to-determine-whether-fastq-files-are-already-demultiplexed/13997/14](https://forum.qiime2.org/t/how-to-determine-whether-fastq-files-are-already-demultiplexed/13997/14)
