### ISSUE TITLE
file not found when running cellranger with a smb cifs mount share

### ISSUE THREAD

**Issue by aurelBZH** [10XGenomics/cellranger#96]
Hi,
i really appreciate your software, i use for featurebarcoding and vdj assessment on single cell data.
I have cellranger-4.0 installed on a virtual machine, it works perfectly when i run it on data uploaded on the virtual machine but when i try to run it on data stored on a server mounted on the virtual machin with cifs cellranger return the error message below:

error: No input FASTQs were found for the requested parameters.

even when i try with a symbolic link it don't work either.

the smbshare server is mounted with : 
sudo mount -t cifs -o user=<username>,uid=<username> //ip/RepSeq /RepSeq/

any help would be very much appreciated

thanks in advance 

Aurélien Béliard 
Bioinformatician 
sorbonne university
i3lab

**Comment by evolvedmicrobe** [comment]
Hi, please contact support@10xgenomics.com for more help with this issue.
