### ISSUE TITLE
Loupeserver encountered an error

### ISSUE THREAD

**Issue by RyanYip-Kat** [10XGenomics/cellranger#97]
![image](https://user-images.githubusercontent.com/67267063/98059499-3e9d2580-1e82-11eb-972a-a6a20cc89ace.png)
I run cellranger reanalyze with my h5 matrix file,and I run successully,but when I opened the cloupe file,I got these error.

![image](https://user-images.githubusercontent.com/67267063/98059647-9471cd80-1e82-11eb-9220-f0c8428f1e7f.png)

**Comment by evolvedmicrobe** [comment]
Hi @RyanYip-Kat, please contact support@10xgenomics.com for further help.
