### ISSUE TITLE
How to add my own barcode whitelist？

### ISSUE THREAD

**Issue by listen2099** [10XGenomics/cellranger#98]
I am testing a dataset with follow Fastq header and Reads structure, but cellranger count complains "an extremely low rate of correct barcodes was observed for this chemistry", It seems that cellranger do not support my data, how can I add DEFINED library information in cellranger count?

**Index: 8 bp
Read1: 30 bp = 20 barcode + 10 UMI
Read2: 90 bp**

**x108_S1_L001_I1_001.fastq.gz**
@MGISEQ:1:DP8400011054TL:1:731589:57:53 1:N:0:AGGTTGGG
AGGTTGGG
+
FFFFFFFF
@MGISEQ:1:DP8400011054TL:1:533701:57:49 1:N:0:AGCATCCA
AGCATCCA
+
FFFFFFFF
@MGISEQ:1:DP8400011054TL:1:731626:57:53 1:N:0:CTGAGTAT
CTGAGTAT

**x108_S1_L001_R1_001.fastq.gz**
@MGISEQ:1:DP8400011054TL:1:731589:57:53 1:N:0:AGGTTGGG
GCCTGTGCGTTACGAAGTGCAGGCATTTGC
+
DDDEE?EEDD?GHEFE>@DFDF;6F/FFE8
@MGISEQ:1:DP8400011054TL:1:533701:57:49 1:N:0:AGCATCCA
GTGAGCGGAAATGTCCGTGCATGCAGATGT
+
FAEEFEFA9CDFEHFFFAEEGF@CEEBHEC
@MGISEQ:1:DP8400011054TL:1:731626:57:53 1:N:0:CTGAGTAT
GTGTCGCGGAAGCAAGCGACTACGTCACGT

**x108_S1_L001_R2_001.fastq.gz**
@MGISEQ:1:DP8400011054TL:1:731589:57:53 2:N:0:AGGTTGGG
CTGTGGGACCTGTGTGCTGGGCAAGGGAGTCTGTCCATCTGCCTGTGTTCGCATACCTAGACTTTTCCAGGGTTTCCAGAAACAGAGAAA
+
DFFDFDDEFEEDAGDFEEEDEFFEE?BEEEDECDDEFFFFGEFDEEGEEFCEFEEEEGGADEGD3EDEEGEEDCEBEGEFFEEHDEEEGE
@MGISEQ:1:DP8400011054TL:1:533701:57:49 2:N:0:AGCATCCA
GTCTCTATCTAAAAAATATAAGGGGCTGGAGATACAGGTCAGAGGTTAAGAACATACATTGTGCTTTCAGAGAACTCAAGTACTATTCCT
+
CADGEEFEEGEDFCEBFFEEFDEDEFDDC8B:EFEF>CDFFDBEEDEDDE5FDDFFDEFFD9EFFFEEGDDE)EFEFGDECFDFG2E<FF
@MGISEQ:1:DP8400011054TL:1:731626:57:53 2:N:0:CTGAGTAT
TATATGTTTCTCTGAACCTGACCTCCCTCTACAACAGTATCTTTCTAGTTGAGTACTAGGATTTAAAACAAACAAACAAACAAGGCCCCA

**Comment by evolvedmicrobe** [comment]
The Cell Ranger software (as discussed in the license) does not support non-10X generate data except under some conditions.  Email support@10xgenomics.com for more help and information.

**Comment by chentingwei908** [comment]
Hello, I recently encountered a similar problem with you. The result of CellRanger seems to show that the comparison rate of barcode is too low. We use the single-cell reference genome of rhesus monkey established by ourselves. I'd like to know if you have solved this problem. I'm looking forward to your reply. Thank you
